//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aws.im.se/otp", ConfigurationName="OTPClient.OtpPortType")]
    public interface OtpPortType {
        
        // CODEGEN: Generating message contract since the operation Otp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpResponse1 Otp(Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aws.im.se/otp")]
    public partial class OtpRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginIdField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
                this.RaisePropertyChanged("loginId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aws.im.se/otp")]
    public partial class OtpResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string otpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string otp {
            get {
                return this.otpField;
            }
            set {
                this.otpField = value;
                this.RaisePropertyChanged("otp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OtpRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aws.im.se/otp", Order=0)]
        public Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpRequest OtpRequest;
        
        public OtpRequest1() {
        }
        
        public OtpRequest1(Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpRequest OtpRequest) {
            this.OtpRequest = OtpRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OtpResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aws.im.se/otp", Order=0)]
        public Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpResponse OtpResponse;
        
        public OtpResponse1() {
        }
        
        public OtpResponse1(Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpResponse OtpResponse) {
            this.OtpResponse = OtpResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OtpPortTypeChannel : Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OtpPortTypeClient : System.ServiceModel.ClientBase<Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpPortType>, Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpPortType {
        
        public OtpPortTypeClient() {
        }
        
        public OtpPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OtpPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OtpPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OtpPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpResponse1 Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpPortType.Otp(Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpRequest1 request) {
            return base.Channel.Otp(request);
        }
        
        public Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpResponse Otp(Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpRequest OtpRequest) {
            Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpRequest1 inValue = new Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpRequest1();
            inValue.OtpRequest = OtpRequest;
            Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpResponse1 retVal = ((Imi.SupplyChain.Services.OrderManagement.OTP.ServiceImplementation.OTPClient.OtpPortType)(this)).Otp(inValue);
            return retVal.OtpResponse;
        }
    }
}
