     select COMPANY.COMPANY_NAME
           ,COMPANY.COMPANY_ID
           ,COMPANY.HOSTINTFACETYPE
           ,COMPANYWH.WHID
       from COMPANY, COMPANYWH, COMPANYEMP
      where COMPANY.COMPANY_ID = COMPANYWH.COMPANY_ID
	    and COMPANY.COMPANY_ID = COMPANYEMP.COMPANY_ID
        and COMPANYEMP.EMPID   = :EMPID 
    order by COMPANY.COMPANY_NAME
