     select COMPANY.COMPANY_NAME
           ,COMPANY.COMPANY_ID
           ,COMPANY.HOSTINTFACETYPE
           ,COMPANYWH.WHID
       from COMPANY, COMPANYWH
	   where COMPANY.COMPANY_ID = COMPANYWH.COMPANY_ID
    order by COMPANY.COMPANY_NAME
