/*
  File           : 

  Description    : Interface classes for inbound data.

 * 061219 5.1.16    olla    dotnet2.0 conversion

*/
using System;
using System.Data;
using System.Xml.Serialization;

namespace Imi.Wms.WebServices.ExternalInterface
{
    /* Note!
     * The 5.0.18 interface was originally built for DotNet 1.1. DotNet 1.1 did NOT support @int etc,
     * which forced us to have our own classes. These are kept in this interface for backward compatibility.
     * Other use is not recommended.
     * */

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class @int
    {
        [XmlText]
        public int Value;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class @double
    {
        [XmlText]
        public double Value;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class dateTime
    {
        [XmlText]
        public System.DateTime Value;
    }

    public class ExternalInterface
    {
        public string _Debug()
        {
            return "Generated on   : 2005-09-16 11:44:01\r\n" +
                   "Generated by   : IMINT1\\olla@IMIPC1091\r\n" +
                   "Generated in   : C:\\project\\views\\olla_temp_ss\\client\\C#\\wscc\r\n";
        }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductStockGroupDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                    /* .                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductStockGroupIdentity; /* ARTGRP.ARTGROUP   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductStockGroupName;     /* ARTGRP.ARTGRPNAME */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class CustomerReturnOrderHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                      /* .                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;   /* RCVHEAD.CROID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence; /* RCVHEAD.CROSEQ       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderType;     /* RCVHEAD.POTYPID      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ScheduledArrivalDateTime;    /* RCVHEAD.EXPARRDTM    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TransportMethod;             /* RCVHEAD.TRPMETH      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string HostStatus;                  /* RCVHEAD.MSPOSTAT     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorNumber;                /* RCVHEAD.SUPID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;           /* RCVHEAD.WHID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseReceiveArea;        /* WS.WSID              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseDock;               /* WD.DOCKID            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                /* RCVHEAD.INSTRUCTIONS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Division;                    /* RCVHEAD.DIVISION     */


        public CustomerReturnOrderLineDoc[] aCustomerReturnOrderLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class CustomerReturnOrderLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* RCVROW.CROID              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* RCVROW.CROSEQ             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* RCVROW.CROPOS             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* RCVROW.CROKITPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* RCVROW.CROSUBPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;                 /* RCVROW.OWNID              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                 /* RCVROW.ARTID              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductDescription;            /* RCVROW.ARTNAME            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorProductNumber;           /* RCVROW.SUPARTID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ScheduledArrivalDateTime;      /* RCVROW.EXPARRDTM          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* RCVROW.BASPAKID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CustomerReturnQuantity;        /* RCVROW.ORDQTY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;          /* RCVROW.PROMOTN            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CustomerReturnPrice;           /* RCVROW.PURPRICE           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;           /* RCVROW.BLOCKCOD           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InventoryStatusDays;           /* RCVROW.BLOCKDAYS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                  /* RCVROW.INSTRUCTIONS       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalOrderIdentity;         /* RCVROW.ORIGINPOID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OriginalOrderLinePosition;     /* RCVROW.ORIGINPOPOS        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalCustomerReference;     /* RCVROW.ORIGINCUSREF       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerQualifier;       /* RCVROW.SHIPTOCUSQUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerIdentity;        /* RCVROW.SHIPTOCUSID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerQualifier;       /* RCVROW.SELLTOCUSQUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerIdentity;        /* RCVROW.SELLTOCUSID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ActionCode;                    /* RCVROW.ACTCODID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReasonCode;                    /* RCVROW.REASONCODE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyId;                   /* RCVROW.FROMPARTYID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyQualifier;            /* RCVROW.FROMPARTYQUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoVendorIdentity;          /* RCVROW.SHIPTOSUPID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoVendorQualifier;         /* RCVROW.SHIPTOSUPQUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;           /* RCVROW.COID               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;     /* RCVROW.COPOS              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;     /* RCVROW.COSUBPOS           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ActionCodeRequirement;         /* RCVROW.ACTCODREQ          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double QuantityUpperTolerance;        /* RCVROW.ORDQTYUPTOL        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureLowerTolerance;    /* RCVROW.MEASQTYLOTOL       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureUpperTolerance;    /* RCVROW.MEASQTYUPTOL       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;         /* RCVROW.PRODLOT            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;      /* RCVROW.PRODSUBLOT         */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class StocktakingOrderDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;            /* .           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity; /* STORD.WHID  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;     /* STORD.ARTID */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ChangeDate;        /* STORD.FPDTM */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PurchaseOrderHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                   /* .                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;      /* RCVHEAD.POID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;    /* RCVHEAD.POSEQ        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderType;        /* RCVHEAD.POTYPID      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ScheduledArrivalDateTime; /* RCVHEAD.EXPARRDTM    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TransportMethod;          /* RCVHEAD.TRPMETH      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string HostStatus;               /* RCVHEAD.MSPOSTAT     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorNumber;             /* RCVHEAD.SUPID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;        /* RCVHEAD.WHID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;             /* RCVHEAD.INSTRUCTIONS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Division;                 /* RCVHEAD.DIVISION     */


        public PurchaseOrderLineDoc[] aPurchaseOrderLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PurchaseOrderLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                       /* .                           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;          /* RCVROW.POID                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;        /* RCVROW.POSEQ                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLinePosition;    /* RCVROW.POPOS                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLineSequence;    /* RCVROW.POSUBPOS             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;                /* RCVROW.OWNID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                /* RCVROW.ARTID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductDescription;           /* RCVROW.ARTNAME              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorProductNumber;          /* RCVROW.SUPARTID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ScheduledArrivalDateTime;     /* RCVROW.EXPARRDTM            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;              /* RCVROW.BASPAKID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PurchaseQuantity;             /* RCVROW.ORDQTY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;        /* RCVROW.PRODLOT              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;     /* RCVROW.PRODSUBLOT           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;         /* RCVROW.PROMOTN              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PurchasePrice;                /* RCVROW.PURPRICE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerQualifier;      /* RCVROW.SHIPTOCUSQUALIFIER   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerIdentity;       /* RCVROW.SHIPTOCUSID          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyQualifier;         /* RCVROW.SHIPTOPARTYQUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyIdentity;          /* RCVROW.SHIPTOPARTYID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;          /* RCVROW.COID                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;        /* RCVROW.COSEQ                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;    /* RCVROW.COPOS                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition; /* RCVROW.COROWKITPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;    /* RCVROW.COSUBPOS             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;          /* RCVROW.BLOCKCOD             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InventoryStatusDays;          /* RCVROW.BLOCKDAYS            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                 /* RCVROW.INSTRUCTIONS         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime DeliveryWindowFirst;          /* RCVROW.FARRDTM              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime DeliveryWindowLast;           /* RCVROW.LARRDTM              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalOrderIdentity;        /* RCVROW.ORIGINPOID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OriginalOrderLinePosition;    /* RCVROW.ORIGINPOPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalCustomerReference;    /* RCVROW.ORIGINCUSREF         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerQualifier;      /* RCVROW.SELLTOCUSQUALIFIER   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerIdentity;       /* RCVROW.SELLTOCUSID          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageLotIdentity;           /* RCVROW.STORBAT              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double QuantityUpperTolerance;       /* RCVROW.ORDQTYUPTOL          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureLowerTolerance;   /* RCVROW.MEASQTYLOTOL         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureUpperTolerance;   /* RCVROW.MEASQTYUPTOL         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Delta_PurchaseQuantity;       /* RCVROW.ORDQTY               */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class CustomerOrderHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                 /* .                      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;    /* CO.COID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;  /* CO.COSEQ               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderType;      /* CO.COTYPE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderClass;     /* CO.COTYPID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderReference; /* CO.CO_REF              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BilltoCustomerIdentity; /* CO.BILLTOCUSID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerIdentity; /* CO.SELLTOCUSID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerIdentity; /* CO.SHIPTOCUSID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PickPriority;           /* CO.PICKPRI             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double DispatchFee;            /* CO.DISPATCH_FEE        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CODFee;                 /* CO.COD_FEE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double FreightCost;            /* CO.FREIGHT_COST        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FreightPartyQualifier;  /* CO.FRE_PARTY_QUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FreightPartyIdentity;   /* CO.FRE_PARTY_ID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Division;               /* CO.DIVISION            */


        public CustomerOrderTextDoc[] aCustomerOrderTextDocs;
        public CustomerOrderLineDoc[] aCustomerOrderLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class CustomerOrderTextDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                /* .                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;   /* CO.COID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence; /* CO.COSEQ            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TextFunction;          /* COFTX.FTX_QUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Text;                  /* COFTX.TEXT          */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class CustomerOrderLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;           /* COROW.COID                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;         /* COROW.COSEQ                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;     /* COROW.COPOS                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition;  /* COROW.COROWKITPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;     /* COROW.COSUBPOS             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderLineType;         /* COROW.COROWTYPE            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Kitproduct;                    /* COROW.KITPRODUCT           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyQualifier;          /* COROW.SHIPTOPARTYQUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyIdentity;           /* COROW.SHIPTOPARTYID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerSubAddress;      /* COROW.SHIPSUBADRID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime RequestedShipdate;             /* COROW.REQSHIPDATE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime AcknowledgedShipdate;          /* COROW.ACKSHIPDATE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime RequestedDeliveryDate;         /* COROW.REQDLVRYDATE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime AcknowledgedDeliveryDate;      /* COROW.ACKDLVRYDATE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;             /* COROW.WHID                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                 /* COROW.ARTID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;                 /* COROW.OWNID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotRequireMent;      /* COROW.PRODLOTREQ           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;          /* COROW.PROMOTN              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageLotIdentity;            /* COROW.STORBAT              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* COROW.PAKID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OrderedQuantity;               /* COROW.ORDQTY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OrderedQuantityTolerancePlus;  /* COROW.ABALDIFF_PLUS        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OrderedQuantityToleranceMinus; /* COROW.ABALDIFF_MINUS       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double KitDetailQuantity;             /* COROW.KITDETAILQTY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ForcePackage;                  /* COROW.PAKFRCE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SerialNumberHandling;          /* COROW.SERIAL               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SerialNumber;                  /* COROW.SERNUMB              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double VATPercent;                    /* COROW.VAT_PERCENT          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DeliveryMethod;                /* COROW.DLVRYMETH_ID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Measure;                       /* COROW.MEASURE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MeasureQualifier;              /* COROW.MEASURE_QUALIFIER    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double SalesPrice;                    /* COROW.PRICE1               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double LineTotal;                     /* COROW.PRICE2               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerProductNumber;   /* COROW.SHIPTOCUSARTID       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;           /* COROW.POID                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;         /* COROW.POSEQ                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLinePosition;     /* COROW.POPOS                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLineSequence;     /* COROW.POSUBPOS             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalOrderIdentity;         /* COROW.ORIGINPOID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OriginalOrderLinePosition;     /* COROW.ORIGINPOPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DepartureLoadIdentity;         /* COROW.DEPLOAD_ID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PlanLoad;                      /* COROW.PLAN_LOAD            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DateSelectionType;             /* COROW.DATE_SELECTION_TYPE  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime FirstPlannedDeliveryDtm;       /* COROW.FPDELDTM             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime LastPlannedDeliveryDtm;        /* COROW.LPDELDTM             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime FirstPlannedShipDtm;           /* COROW.FPSHIPDTM            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime LastPlannedShipDtm;            /* COROW.LPSHIPDTM            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentityAtShipToCustomer; /* COROW.OWNID_SHIPTOCUS      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;           /* COROW.BLOCKCOD             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OrderedQuantityLowerTolerance; /* COROW.ORDQTYLOTOL          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OrderedQuantityUpperTolerance; /* COROW.ORDQTYUPTOL          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureLowerTolerance;    /* COROW.MEASQTYLOTOL         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureUpperTolerance;    /* COROW.MEASQTYUPTOL         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;         /* COROW.PRODLOT              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;      /* COROW.PRODSUBLOT           */


        public CustomerOrderLineTextDoc[] aCustomerOrderLineTextDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class CustomerOrderLineTextDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                       /* .                      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;          /* COROW.COID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;        /* COROW.COSEQ            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;    /* COROW.COPOS            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition; /* COROW.COROWKITPOS      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;    /* COROW.COSUBPOS         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TextFunction;                 /* COROWFTX.FTX_QUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Text;                         /* COROWFTX.TEXT          */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PartyDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE; /* . */


        public VendorDoc[] aVendorDocs;
        public CustomerDoc[] aCustomerDocs;
        public PartyAddressDoc[] aPartyAddressDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class VendorDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;       /* .           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorNumber; /* SUP.SUPID   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorName;   /* SUP.SUPNAME */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class CustomerDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;         /* .            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerNumber; /* CUS.CUSID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerName1;  /* CUS.CUSNAME1 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerName2;  /* CUS.CUSNAME2 */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PartyAddressDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;             /* .                       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyQualifier;     /* PARTY.PARTY_QUALIFIER   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyIdentity;      /* PARTY.PARTY_ID          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyProfile;       /* PARTY.PARTY_PROFILE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyStatus;        /* PARTY.PARTY_STAT        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyName1;         /* PARTY.NAME1             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyName2;         /* PARTY.NAME2             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyName3;         /* PARTY.NAME3             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyName4;         /* PARTY.NAME4             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyName5;         /* PARTY.NAME5             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyAddress1;      /* PARTY.ADR1              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyAddress2;      /* PARTY.ADR2              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyAddress3;      /* PARTY.ADR3              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PartyAddress4;      /* PARTY.ADR4              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ZipCode;            /* PARTY.POSTCODE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string City;               /* PARTY.CITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Region;             /* PARTY.REGION            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CountryCode;        /* PARTY.COUNTRYCODE       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Country;            /* PARTY.COUNTRY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string GeographicalCode;   /* PARTY.GEOREF            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Phone;              /* PARTY.PHONE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Fax;                /* PARTY.FAX               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Telex;              /* PARTY.TELEX             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Email;              /* PARTY.EMAIL             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PostalGiroAccount;  /* PARTY.POSTAL_GIRO_ACCNT */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BankGiroAccount;    /* PARTY.BANK_GIRO_ACCNT   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VATNumber;          /* PARTY.VAT_NUMBER        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OrganizationNumber; /* PARTY.ORG_NUMBER        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Language;           /* PARTY.LNGID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Division;           /* PARTY.DIVISION          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SendASN;            /* PARTY.SENDASN           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RcvCheckType;       /* PARTY.RCV_CHECK_TYPE    */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class InventoryStatusDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                   /* .                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;      /* BLOCKCOD.BLOCKCOD   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusName;      /* BLOCKCOD.BLOCKCODNM */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusAutoReset; /* BLOCKCOD.AUTORESET  */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class VendorReturnOrderHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                    /* .               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorReturnOrderNumber;   /* SO.SOID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int VendorReturnOrderSequence; /* SO.SOSEQ        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseId;               /* SO.WHID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorId;                  /* SO.SUPID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime RequestedShipDate;         /* SO.ACKSHIPDATE  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;              /* SO.INSTRUCTIONS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DeliveryMethod;            /* SO.DLVRYMETH_ID */


        public VendorReturnOrderLineDoc[] aVendorReturnOrderLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class VendorReturnOrderLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorReturnOrderNumber;       /* SOROW.SOID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int VendorReturnOrderSequence;     /* SOROW.SOSEQ            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int VendorReturnOrderLine;         /* SOROW.SOROWPOS         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int VendorReturnOrderLineSeq;      /* SOROW.SOROWSEQ         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                 /* SOROW.ARTID            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* SOROW.PAKID            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;         /* SOROW.PRODLOT          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;      /* SOROW.PRODSUBLOT       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;          /* SOROW.PROMOTN          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;                 /* SOROW.OWNID            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double ReturnQuantity;                /* SOROW.ORDQTY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ClaimCause;                    /* SOROW.CLAIM_CAUSE      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ClaimCauseText;                /* SOROW.CLAIM_CAUSE_TEXT */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ClaimCauseCode;                /* SOROW.CLAIM_CAUSE_CODE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                  /* SOROW.INSTRUCTIONS     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* SOROW.CROID            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* SOROW.CROSEQ           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* SOROW.CROPOS           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* SOROW.CROKITPOS        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* SOROW.CROSUBPOS        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;           /* SOROW.BLOCKCOD         */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ASNHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                       /* .                             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ASNIdentity;                  /* RCVHEAD.ASNINID               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNSequenceNumber;            /* RCVHEAD.ASNINSEQ              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;    /* RCVHEAD.SHIPFROMPARTYNODEID   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ASNLevel;                     /* RCVHEAD.RCVTYPE               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ShipDateTime;                 /* RCVHEAD.SHIPDTM               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime DocumentDateTime;             /* RCVHEAD.DOCDTM                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime DeliveryWindowFirst;          /* RCVHEAD.FARRDTM               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime DeliveryWindowLast;           /* RCVHEAD.LARRDTM               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime RequestedArrivalDateTime;     /* RCVHEAD.RARRDTM               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ScheduledArrivalDateTime;     /* RCVHEAD.EXPARRDTM             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ForwarderIdentity;            /* RCVHEAD.FREID                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int NumberOfLoadCarriers;         /* ASNOUT.NOCARS                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double EstimatedVolume;              /* ASNOUT.ESTVOLUME              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VolumeUOMIdentity;            /* ASNOUT.UNIT_VOLUME            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                 /* RCVHEAD.INSTRUCTIONS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VehicleIdentity;              /* RCVHEAD.TRUCKID               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BillOfLadingNumber;           /* RCVHEAD.CONSNOTE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackingSlipNumber;            /* RCVHEAD.DLVRYNOTE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;        /* RCVHEAD.SHIPFROMPARTYID       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyQualifier;       /* ASNOUT.SHIPFROMPARTYQUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyIdentity;          /* RCVHEAD.SHIPFROMPARTYID       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyQualifier;         /* ASNOUT.SHIPTOPARTYQUALIFIER   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyNodeIdentity;      /* ASNOUT.SHIPTOPARTYNODEID      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShippedFromWarehouseIdentity; /* ASNOUT.WHID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShippedOnDepartureIdentity;   /* ASNOUT.DEPARTURE_ID           */


        public ASNLoadCarrierDoc[] aASNLoadCarrierDocs;
        public ASNLineDoc[] aASNLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ASNLoadCarrierDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                     /* .                              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ASNIdentity;                /* RCVHEAD.ASNINID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNSequenceNumber;          /* RCVHEAD.ASNINSEQ               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;  /* RCVHEAD.SHIPFROMPARTYNODEID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierIdentity;        /* RCVCAR.CARID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierQualifier;       /* ASNOUTCAR.CARID_QUALIFIER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierType;            /* RCVCAR.CARTYPID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ExternalLoadCarrierType;    /* RCVCAR.CARTYPID2               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ParentLoadCarrierIdentity;  /* RCVCAR.CARCARID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToCustomerNodeIdentity; /* RCVCAR.SHIPTOCUSNODEID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToCustomerIdentity;     /* RCVCAR.SHIPTOCUSID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToCustomerQualifier;    /* RCVCAR.SHIPTOCUSQUALIFIER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;               /* RCVCAR.INSTRUCTIONS            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double TotalWeight;                /* RCVCAR.TOTWGT                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WeightUOMIdentity;          /* UNIT.UNIT_ID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double TotalVolume;                /* RCVCAR.TOTVOL                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VolumeUOMIdentity;          /* UNIT.UNIT_ID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double TotalHeight;                /* RCVCAR.TOTHGT                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string HeightUOMIdentity;          /* UNIT.UNIT_ID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductTransportIdentity;   /* RCVCAR.ARTTRPTYPID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;      /* RCVCAR.SHIPFROMPARTYID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyIdentity;        /* ASNOUTCAR.SHIPTOPARTYID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyNodeIdentity;    /* ASNOUTCAR.SHIPTOPARTYNODEID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyQualifier;       /* ASNOUTCAR.SHIPTOPARTYQUALIFIER */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ASNLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ASNIdentity;                   /* RCVROW.ASNINID                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNSequenceNumber;             /* RCVROW.ASNINSEQ                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;     /* RCVROW.SHIPFROMPARTYNODEID     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNLineNumber;                 /* RCVROW.ASNINROWID              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNLineSequenceNumber;         /* RCVROW.ASNINROWSEQ             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierIdentity;           /* RCVROW.CARID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;                 /* RCVROW.OWNID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumberShipFromPartner;  /* RCVROW.ARTID_SHIPFROMPARTNER   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumberShipToPartner;    /* RCVROW.ARTID_SHIPTOPARTNER     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string GlobalProductNumber;           /* RCVROW.ARTID_GLOBAL            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ExpiryDate;                    /* RCVROW.EXPIRYDATE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ManufacturingDate;             /* RCVROW.MANUFACTURINGDATE       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;         /* RCVROW.PRODLOT                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;      /* RCVROW.PRODSUBLOT              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;          /* RCVROW.PROMOTN                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageLot;                    /* RCVROW.STORBAT                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SerialNumber;                  /* RCVROW.SERNUMB                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double ShippedQuantity;               /* RCVROW.ORDQTY                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Volume;                        /* RCVROW.ESTVOLUME               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VolumeUOMIdentity;             /* UNIT.UNIT_ID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Weight;                        /* RCVROW.WEIGHT                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WeightUOMIdentity;             /* UNIT.UNIT_ID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;           /* RCVROW.POID                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;         /* RCVROW.POSEQ                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLinePos;          /* RCVROW.POPOS                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLineSeq;          /* RCVROW.POSUBPOS                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                  /* RCVROW.INSTRUCTIONS            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorIdentity;                /* RCVROW.SUPID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorPartyNodeIdentity;       /* RCVROW.SUP_PARTYNODEID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PredefinedItemLoadIdentity;    /* RCVROW.ITEID_PRE               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MeasuredQuantity;              /* RCVROW.MEASQTY                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MeasureQualifier;              /* RCVROW.MEASURE_QUALIFIER       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AdditionalPackingMaterial;     /* RCVROW.ADDITIONAL_PM           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;         /* RCVHEAD.SHIPFROMPARTYID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyIdentity;           /* RCVROW.SHIPTOPARTYID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyNodeIdentity;       /* ASNOUTROW.SHIPTOPARTYNODEID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyQualifier;          /* ASNOUTROW.SHIPTOPARTYQUALIFIER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderType;             /* RCVROW.COTYPE                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StockedProductNumber;          /* RCVROW.ARTIDSALEABLE           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string GlobalStockedProductNumber;    /* RCVROW.ARTIDSALEABLE_GLOBAL    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ActionCode;                    /* RCVROW.ACTCODID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReasonCode;                    /* RCVROW.REASONCODE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReasonText;                    /* RCVROW.REASONTEXT              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyIdentity;             /* RCVROW.FROMPARTYID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyQualifier;            /* RCVROW.FROMPARTYQUALIFIER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* RCVROW.CROID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* RCVROW.CROSEQ                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* RCVROW.CROPOS                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* RCVROW.CROKITPOS               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* RCVROW.CROSUBPOS               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToVendorIdentity;          /* RCVROW.SHIPTOSUPID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToVendorQualifier;         /* RCVROW.SHIPTOSUPQUALIFIER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ActionCodeRequirement;         /* RCVROW.ACTCODREQ               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;           /* RCVROW.COID                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;         /* RCVROW.COSEQ                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;     /* RCVROW.COPOS                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;     /* RCVROW.COSUBPOS                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition;  /* RCVROW.COROWKITPOS             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentityAtShipToCustomer; /* RCVROW.OWNID_SHIPTOCUS         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalPurchaseOrderNumber;   /* RCVROW.ORIGINPOID              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int OriginalPurchaseOrderSequence; /* RCVROW.ORIGINPOSEQ             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OriginalPurchaseOrderLinePos;  /* RCVROW.ORIGINPOPOS             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int OriginalPurchaseOrderLineSeq;  /* RCVROW.ORIGINPOSUBPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalCustomerReference;     /* RCVROW.ORIGINCUSREF            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventorystatusCode;           /* RCVROW.BLOCKCOD                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InventorystatusDays;           /* RCVROW.BLOCKDAYS               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventorystatusKey;            /* RCVROW.BLOCKKEY                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventorystatusText;           /* RCVROW.BLOCKTXT                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime InventorystatusAlarmDate;      /* RCVROW.ALMDATE                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double DiscrepancyQuantity;           /* ASNOUTROW.RESTQTY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DiscrepancyCode;               /* ASNOUTROW.RESTCOD              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DiscrepancyText;               /* ASNOUTROW.RESTCODTXT           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerNodeIdentity;    /* RCVROW.SHIPTOCUSNODEID         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerIdentity;        /* RCVROW.SHIPTOCUSID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerQualifier;       /* RCVROW.SHIPTOCUSQUALIFIER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerIdentity;        /* RCVROW.SELLTOCUSID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerQualifier;       /* RCVROW.SELLTOCUSQUALIFIER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                 /* RCVROW.ARTID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductDescription;            /* RCVROW.ARTNAME                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumberType;             /* RCVROW.ARTIDQUALIFIER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AlternativeProductNumber;      /* RCVROW.ARTID2                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AlternativeProductDescription; /* RCVROW.ARTNAME2                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ProductDate;                   /* RCVROW.ARTDATE                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorProductNumber;           /* RCVROW.SUPARTID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PurchasePrice;                 /* RCVROW.PURPRICE                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* RCVROW.BASPAKID                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double QuantityUpperTolerance;        /* RCVROW.ORDQTYUPTOL             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureLowerTolerance;    /* RCVROW.MEASQTYLOTOL            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureUpperTolerance;    /* RCVROW.MEASQTYUPTOL            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ManufacturingUnit;             /* RCVROW.PRODUNIT                */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class BalanceQueryDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;            /* .            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity; /* ARTQRY.WHID  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;     /* ARTQRY.OWNID */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;     /* ARTQRY.ARTID */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MessageNumber;     /* ARTQRY.MSGNO */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE; /* . */


        public ProductGlobalDoc[] aProductGlobalDocs;
        public ProductNumberDoc[] aProductNumberDocs;
        public ProductDescriptionDoc[] aProductDescriptionDocs;
        public ProductInWarehouseDoc[] aProductInWarehouseDocs;
        public ProductPackageDoc[] aProductPackageDocs;
        public ProductBarcodeDoc[] aProductBarcodeDocs;
        public ProductVendorDoc[] aProductVendorDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductGlobalDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                 /* ART.ARTID                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductDescription1;           /* ART.ARTNAME1              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductDescription2;           /* ART.ARTNAME2              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductStockGroupIdentity;     /* ART.ARTGROUP              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductType;                   /* ART.ARTTYPID              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductDateType;               /* ART.ARTDTYPE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ProductShipDateLeadTime;       /* ART.ARTLEAD2              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ProductDeliveryDateLeadTime;   /* ART.ARTLEAD1              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ProductManufacturDateLeadTime; /* ART.ARTLEAD3              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotHandling;         /* ART.PRODLOT_OUT           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotHandling;          /* .                         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageLotHandling;            /* ART.STORBAT_OUT           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SerialNumberHandling;          /* ART.SERIAL                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int FIFOAllowedDiscrepancy;        /* ART.FIFOPLUS              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                  /* ART.INSTRUCTIONS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductSaleable;               /* PMTYP.ARTIDSALEABLE       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotHandling_In;      /* ART.PRODLOT_IN            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotHandling_In;       /* ART.PROMOTN_IN            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageLotHandling_In;         /* ART.STORBAT_IN            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotVerify;           /* ART.PRODLOT_VER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductTransportIdentity;      /* ART.ARTTRPTYPID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CatchMeasure;                  /* ART.MEASURE               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CatchMeasureQualifier;         /* ART.MEASURE_QUALIFIER     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CatchMeasureRcv;               /* ART.MEASURE_RCV           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CatchMeasureQualifierRcv;      /* ART.MEASURE_QUALIFIER_RCV */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductNumberDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                  /* .                      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AdditionalNumberType;    /* ARTNUM.ART_NUMBER_TYPE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AdditionalProductNumber; /* ARTNUM.ART_NUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;           /* ARTNUM.ARTID           */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductDescriptionDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;        /* .                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber; /* ARTDESCR.ARTID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Language;      /* ARTDESCR.LNGID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description1;  /* ARTDESCR.ARTNAME1 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description2;  /* ARTDESCR.ARTNAME2 */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductInWarehouseDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                      /* .                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;               /* ARTWH.ARTID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;           /* ARTWH.WHID            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InventoryAuditFrequency;     /* ARTWH.STFREQ_ITEM     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StockedProduct;              /* ARTWH.STOCKEDPRODUCT  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;               /* ARTWH.OWNID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int StorageTemperatureMin;       /* ARTWH.STORMINTEMP     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int StorageTemperatureMax;       /* ARTWH.STORMAXTEMP     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageTemperatureQualifier; /* ARTWH.TEMPQUALIFIER   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int Frequency;                   /* ARTWH.FREQNCY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                /* ARTWH.INSTRUCTIONS    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string HygieneCheck;                /* ARTWH.HYGCHK          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TemperatureCheck;            /* ARTWH.TEMPCHK         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double RefuseTempHigh;              /* ARTWH.MAXTEMP_REFUSE  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double RefuseTempLow;               /* ARTWH.MINTEMP_REFUSE  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double WarnTempHigh;                /* ARTWH.MAXTEMP_WARNING */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double WarnTempLow;                 /* ARTWH.MINTEMP_WARNING */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageChange;               /* ARTWH.PAKCHNGE        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotHandling;       /* ARTWH.PRODLOT_OUT     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageLotHandling;          /* ARTWH.STORBAT_OUT     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotHandling_In;    /* ARTWH.PRODLOT_IN      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotHandling_In;     /* ARTWH.PROMOTN_IN      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageLotHandling_In;       /* ARTWH.STORBAT_IN      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotVerify;         /* ARTWH.PRODLOT_VER     */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductPackageDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                   /* .                       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;            /* PAK.ARTID               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;          /* PAK.PAKID               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageName;              /* PAK.PAKNAME             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BasePackageIdentity;      /* PAK.BASPAKID            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double NumberofBasePackages;     /* PAK.BASEQTY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double NumberofConsumerPackages; /* PAK.CONSUMERQTY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Weight;                   /* PAK.WEIGHT              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Height;                   /* PAK.HEIGHT              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Length;                   /* PAK.LENGTH              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Width;                    /* PAK.WIDTH               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Volume;                   /* PAK.VOLUME              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PMTYPID_IN;               /* PAK.PMTYPID_IN          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PMTYPID_OUT;              /* PAK.PMTYPID_OUT         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LayerPackage;             /* PAK.LAYERPAK            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int VolumeFillPercent;        /* PAK.VOLUME_FILL_PERCENT */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BarCode;                  /* PAK.EANDUN              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BarCodeType;              /* EAN.BARCODETYPE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PalPak;                   /* PAK.PALPAK              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PalPick;                  /* PAK.PALPICK             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Cartypid;                 /* PAK.CARTYPID            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CarCartypid;              /* PAK.CAR_CARTYPID        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int NoPaksCarCar;             /* PAK.NOPAKS_CARCAR       */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductBarcodeDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;          /* .               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BarCode;         /* EAN.EANDUN      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;   /* EAN.ARTID       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BarcodeType;     /* EAN.BARCODETYPE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity; /* EAN.PAKID       */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ProductVendorDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;              /* .               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorIdentity;      /* ARTSUP.SUPID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;       /* ARTSUP.ARTID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorProductNumber; /* ARTSUP.SUPARTID */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;     /* ARTSUP.PAKID    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CountryOfOrigin;     /* ARTSUP.COOCOD   */


    }
}
