/*
  File           : 

  Description    : Interface classes for inbound data.

 * 061219 5.1.16    olla    dotnet2.0 conversion

*/
using System;
using System.Data;
using System.Xml.Serialization;

namespace Imi.Wms.WebServices.ExternalInterface
{
    /* Note!
     * The 5.0.18 interface was originally built for DotNet 1.1. DotNet 1.1 did NOT support @int etc,
     * which forced us to have our own classes. These are kept in this interface for backward compatibility.
     * Other use is not recommended.
     * */

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class @int
    {
        [XmlText]
        public int Value;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class @double
    {
        [XmlText]
        public double Value;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class dateTime
    {
        [XmlText]
        public System.DateTime Value;
    }

    public class ExternalInterface
    {
        public string _Debug()
        {
            return "Generated on   : 2005-09-21 20:25:49\r\n" +
                   "Generated by   : IMINT1\\olla@IMIPC1091\r\n" +
                   "Generated in   : C:\\project\\views\\olla_temp_ss\\client\\C#\\wscc\r\n";
        }
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class BalanceAnswerLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                    /* .                                             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LastBalanceAnswer;         /* HAPI_BALANCE_ANSWER.LASTBALANCEANSWER         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;         /* HAPI_BALANCE_ANSWER.WAREHOUSEIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;             /* HAPI_BALANCE_ANSWER.OWNERIDENTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;             /* HAPI_BALANCE_ANSWER.PRODUCTNUMBER             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;     /* HAPI_BALANCE_ANSWER.PRODUCTIONLOTIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;  /* HAPI_BALANCE_ANSWER.PRODUCTIONSUBLOTIDENTITY  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;      /* HAPI_BALANCE_ANSWER.MARKETINGLOTIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string QualityLotIdentity;        /* HAPI_BALANCE_ANSWER.QUALITYLOTIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;           /* HAPI_BALANCE_ANSWER.PACKAGEIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;       /* HAPI_BALANCE_ANSWER.INVENTORYSTATUSCODE       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double FreeQuantity;              /* HAPI_BALANCE_ANSWER.FREEQUANTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PickLocationQuantity;      /* HAPI_BALANCE_ANSWER.PICKLOCATIONQUANTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double ReservedForReplenQuantity; /* HAPI_BALANCE_ANSWER.RESERVEDFORREPLENQUANTITY */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PickedQuantity;            /* HAPI_BALANCE_ANSWER.PICKEDQUANTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double TopickQuantity;            /* HAPI_BALANCE_ANSWER.TOPICKQUANTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CustomerReservedQuantity;  /* HAPI_BALANCE_ANSWER.CUSTOMERRESERVEDQUANTITY  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MessageNumber;             /* HAPI_BALANCE_ANSWER.MESSAGENUMBER             */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class DeliveryReceiptHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;             /* .                                          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryIdentity;   /* HAPI_DLVRY_RECEIPT_HEAD.DELIVERYIDENTITY   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ArrivalDateTime;    /* HAPI_DLVRY_RECEIPT_HEAD.ARRIVALDATETIME    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;  /* HAPI_DLVRY_RECEIPT_HEAD.WAREHOUSEIDENTITY  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string EmployeeIdentity;   /* HAPI_DLVRY_RECEIPT_HEAD.EMPLOYEEIDENTITY   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReceiveType;        /* HAPI_DLVRY_RECEIPT_HEAD.RECEIVETYPE        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackingSlipNumber;  /* HAPI_DLVRY_RECEIPT_HEAD.PACKINGSLIPNUMBER  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BillOfLadingNumber; /* HAPI_DLVRY_RECEIPT_HEAD.BILLOFLADINGNUMBER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VehicleIdentity;    /* HAPI_DLVRY_RECEIPT_HEAD.VEHICLEIDENTITY    */


        public DeliveryReceiptLineDoc[] aDeliveryReceiptLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class DeliveryReceiptLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;           /* HAPI_DLVRY_RECEIPT_LINE.INVENTORYSTATUSCODE           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLineSequence;     /* HAPI_DLVRY_RECEIPT_LINE.PURCHASEORDERLINESEQUENCE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderType;             /* HAPI_DLVRY_RECEIPT_LINE.PURCHASEORDERTYPE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;           /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;         /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERORDERSEQUENCE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;     /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERORDERLINEPOSITION     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition;  /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERORDERLINEKITPOSITION  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;     /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERORDERLINESEQUENCE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DespatchadvicenoticeIdentity;  /* HAPI_DLVRY_RECEIPT_LINE.DESPATCHADVICENOTICEIDENTITY  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ItemLoadIdentity;              /* HAPI_DLVRY_RECEIPT_LINE.ITEMLOADIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ExpiryDate;                    /* HAPI_DLVRY_RECEIPT_LINE.EXPIRYDATE                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReturnsFinished;               /* HAPI_DLVRY_RECEIPT_LINE.RETURNSFINISHED               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DecidedActionCode;             /* HAPI_DLVRY_RECEIPT_LINE.DECIDEDACTIONCODE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyId;                   /* HAPI_DLVRY_RECEIPT_LINE.FROMPARTYID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyQualifier;            /* HAPI_DLVRY_RECEIPT_LINE.FROMPARTYQUALIFIER            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERRETURNORDERNUMBER     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERRETURNORDERSEQUENCE   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERRETURNORDERLINEPOS    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERRETURNORDERLINEKITPOS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* HAPI_DLVRY_RECEIPT_LINE.CUSTOMERRETURNORDERLINESEQ    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DiscrepancyCode;               /* HAPI_DLVRY_RECEIPT_LINE.DISCREPANCYCODE               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DiscrepancyActionCode;         /* HAPI_DLVRY_RECEIPT_LINE.DISCREPANCYACTIONCODE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ManufacturingDate;             /* HAPI_DLVRY_RECEIPT_LINE.MANUFACTURINGDATE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MeasureQualifier;              /* HAPI_DLVRY_RECEIPT_LINE.MEASUREQUALIFIER              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryIdentity;              /* HAPI_DLVRY_RECEIPT_LINE.DELIVERYIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryidentityLine;          /* HAPI_DLVRY_RECEIPT_LINE.DELIVERYIDENTITYLINE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ArrivalDateTime;               /* HAPI_DLVRY_RECEIPT_LINE.ARRIVALDATETIME               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductIdentity;               /* HAPI_DLVRY_RECEIPT_LINE.PRODUCTIDENTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* HAPI_DLVRY_RECEIPT_LINE.PACKAGEIDENTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double DeliveredQuantity;             /* HAPI_DLVRY_RECEIPT_LINE.DELIVEREDQUANTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MeasuredQuantity;              /* HAPI_DLVRY_RECEIPT_LINE.MEASUREDQUANTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;         /* HAPI_DLVRY_RECEIPT_LINE.PRODUCTIONLOTIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;      /* HAPI_DLVRY_RECEIPT_LINE.PRODUCTIONSUBLOTIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;          /* HAPI_DLVRY_RECEIPT_LINE.MARKETINGLOTIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string QualityLotIdentity;            /* HAPI_DLVRY_RECEIPT_LINE.QUALITYLOTIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;           /* HAPI_DLVRY_RECEIPT_LINE.PURCHASEORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;         /* HAPI_DLVRY_RECEIPT_LINE.PURCHASEORDERSEQUENCE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLinePosition;     /* HAPI_DLVRY_RECEIPT_LINE.PURCHASEORDERLINEPOSITION     */


        public DeliveryReceiptPackingMaterialDoc[] aDeliveryReceiptPackingMaterialDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class DeliveryReceiptPackingMaterialDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackingMaterialType;           /* HAPI_DLVRY_RECEIPT_PM.PACKINGMATERIALTYPE           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorIdentity;                /* HAPI_DLVRY_RECEIPT_PM.VENDORIDENTITY                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderType;             /* HAPI_DLVRY_RECEIPT_PM.PURCHASEORDERTYPE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* HAPI_DLVRY_RECEIPT_PM.CUSTOMERRETURNORDERSEQUENCE   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* HAPI_DLVRY_RECEIPT_PM.CUSTOMERRETURNORDERLINEPOS    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* HAPI_DLVRY_RECEIPT_PM.CUSTOMERRETURNORDERLINEKITPOS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* HAPI_DLVRY_RECEIPT_PM.CUSTOMERRETURNORDERLINESEQ    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryIdentity;              /* HAPI_DLVRY_RECEIPT_PM.DELIVERYIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ArrivalDateTime;               /* HAPI_DLVRY_RECEIPT_PM.ARRIVALDATETIME               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryidentityLine;          /* HAPI_DLVRY_RECEIPT_PM.DELIVERYIDENTITYLINE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* HAPI_DLVRY_RECEIPT_PM.PACKAGEIDENTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double DeliveredQuantity;             /* HAPI_DLVRY_RECEIPT_PM.DELIVEREDQUANTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;           /* HAPI_DLVRY_RECEIPT_PM.PURCHASEORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;         /* HAPI_DLVRY_RECEIPT_PM.PURCHASEORDERSEQUENCE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;           /* HAPI_DLVRY_RECEIPT_PM.CUSTOMERORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;         /* HAPI_DLVRY_RECEIPT_PM.CUSTOMERORDERSEQUENCE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyId;                   /* HAPI_DLVRY_RECEIPT_PM.FROMPARTYID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyQualifier;            /* HAPI_DLVRY_RECEIPT_PM.FROMPARTYQUALIFIER            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* HAPI_DLVRY_RECEIPT_PM.CUSTOMERRETURNORDERNUMBER     */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class InspectionReceiptHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                /* .                                                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;     /* HAPI_INSPECTION_RECEIPT_HEAD.WAREHOUSEIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string EmployeeIdentity;      /* HAPI_INSPECTION_RECEIPT_HEAD.EMPLOYEEIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ReturnhandleddateTime; /* HAPI_INSPECTION_RECEIPT_HEAD.RETURNHANDLEDDATETIME */


        public InspectionReceiptLineDoc[] aInspectionReceiptLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class InspectionReceiptLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;      /* HAPI_INSPECTION_RECEIPT_LINE.PRODUCTIONSUBLOTIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;          /* HAPI_INSPECTION_RECEIPT_LINE.MARKETINGLOTIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string QualityLotIdentity;            /* HAPI_INSPECTION_RECEIPT_LINE.QUALITYLOTIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ItemLoadIdentity;              /* HAPI_INSPECTION_RECEIPT_LINE.ITEMLOADIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ExpiryDate;                    /* HAPI_INSPECTION_RECEIPT_LINE.EXPIRYDATE                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyId;                   /* HAPI_INSPECTION_RECEIPT_LINE.FROMPARTYID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyQualifier;            /* HAPI_INSPECTION_RECEIPT_LINE.FROMPARTYQUALIFIER            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerIdentity;        /* HAPI_INSPECTION_RECEIPT_LINE.SHIPTOCUSTOMERIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerQualifier;       /* HAPI_INSPECTION_RECEIPT_LINE.SHIPTOCUSTOMERQUALIFIER       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WorkOrderIdentity;             /* HAPI_INSPECTION_RECEIPT_LINE.WORKORDERIDENTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int WorkOrderLine;                 /* HAPI_INSPECTION_RECEIPT_LINE.WORKORDERLINE                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int WorkOrderLineSeq;              /* HAPI_INSPECTION_RECEIPT_LINE.WORKORDERLINESEQ              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductIdentity;               /* HAPI_INSPECTION_RECEIPT_LINE.PRODUCTIDENTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* HAPI_INSPECTION_RECEIPT_LINE.PACKAGEIDENTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double InspectedQuantity;             /* HAPI_INSPECTION_RECEIPT_LINE.INSPECTEDQUANTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DecidedActionCode;             /* HAPI_INSPECTION_RECEIPT_LINE.DECIDEDACTIONCODE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* HAPI_INSPECTION_RECEIPT_LINE.CUSTOMERRETURNORDERNUMBER     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* HAPI_INSPECTION_RECEIPT_LINE.CUSTOMERRETURNORDERSEQUENCE   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* HAPI_INSPECTION_RECEIPT_LINE.CUSTOMERRETURNORDERLINEPOS    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* HAPI_INSPECTION_RECEIPT_LINE.CUSTOMERRETURNORDERLINEKITPOS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* HAPI_INSPECTION_RECEIPT_LINE.CUSTOMERRETURNORDERLINESEQ    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryIdentity;              /* HAPI_INSPECTION_RECEIPT_LINE.DELIVERYIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryidentityLine;          /* HAPI_INSPECTION_RECEIPT_LINE.DELIVERYIDENTITYLINE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MeasuredQuantity;              /* HAPI_INSPECTION_RECEIPT_LINE.MEASUREDQUANTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;           /* HAPI_INSPECTION_RECEIPT_LINE.INVENTORYSTATUSCODE           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;         /* HAPI_INSPECTION_RECEIPT_LINE.PRODUCTIONLOTIDENTITY         */


        public InspectionReceiptLinePackingMaterialDoc[] aInspectionReceiptLinePackingMaterialDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class InspectionReceiptLinePackingMaterialDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WorkOrderIdentity;             /* HAPI_INSPECTION_RECEIPT_LINEPM.WORKORDERIDENTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int WorkOrderLine;                 /* HAPI_INSPECTION_RECEIPT_LINEPM.WORKORDERLINE                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int WorkOrderLineSeq;              /* HAPI_INSPECTION_RECEIPT_LINEPM.WORKORDERLINESEQ              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int WorkOrderLinePmSeq;            /* HAPI_INSPECTION_RECEIPT_LINEPM.WORKORDERLINEPMSEQ            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackingMaterialIdentity;       /* HAPI_INSPECTION_RECEIPT_LINEPM.PACKINGMATERIALIDENTITY       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* HAPI_INSPECTION_RECEIPT_LINEPM.PACKAGEIDENTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double InspectedPmQuantity;           /* HAPI_INSPECTION_RECEIPT_LINEPM.INSPECTEDPMQUANTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DecidedActionCode;             /* HAPI_INSPECTION_RECEIPT_LINEPM.DECIDEDACTIONCODE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* HAPI_INSPECTION_RECEIPT_LINEPM.CUSTOMERRETURNORDERNUMBER     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* HAPI_INSPECTION_RECEIPT_LINEPM.CUSTOMERRETURNORDERSEQUENCE   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* HAPI_INSPECTION_RECEIPT_LINEPM.CUSTOMERRETURNORDERLINEPOS    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* HAPI_INSPECTION_RECEIPT_LINEPM.CUSTOMERRETURNORDERLINEKITPOS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* HAPI_INSPECTION_RECEIPT_LINEPM.CUSTOMERRETURNORDERLINESEQ    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryIdentity;              /* HAPI_INSPECTION_RECEIPT_LINEPM.DELIVERYIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryidentityLine;          /* HAPI_INSPECTION_RECEIPT_LINEPM.DELIVERYIDENTITYLINE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyId;                   /* HAPI_INSPECTION_RECEIPT_LINEPM.FROMPARTYID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyQualifier;            /* HAPI_INSPECTION_RECEIPT_LINEPM.FROMPARTYQUALIFIER            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;           /* HAPI_INSPECTION_RECEIPT_LINEPM.CUSTOMERORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderSequence;         /* HAPI_INSPECTION_RECEIPT_LINEPM.CUSTOMERORDERSEQUENCE         */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class InventoryChangeLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                       /* .                                                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MeasuredQty;                  /* HAPI_INVENTORY_CHANGE.MEASUREDQTY                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MeasuredQty2;                 /* HAPI_INVENTORY_CHANGE.MEASUREDQTY2                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ProductDate;                  /* HAPI_INVENTORY_CHANGE.PRODUCTDATE                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ProductDate2;                 /* HAPI_INVENTORY_CHANGE.PRODUCTDATE2                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorIdentity2;              /* HAPI_INVENTORY_CHANGE.VENDORIDENTITY2              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber2;               /* HAPI_INVENTORY_CHANGE.PRODUCTNUMBER2               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;              /* HAPI_INVENTORY_CHANGE.PACKAGEIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity2;             /* HAPI_INVENTORY_CHANGE.PACKAGEIDENTITY2             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Quantity;                     /* HAPI_INVENTORY_CHANGE.QUANTITY                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Quantity2;                    /* HAPI_INVENTORY_CHANGE.QUANTITY2                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;          /* HAPI_INVENTORY_CHANGE.INVENTORYSTATUSCODE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode2;         /* HAPI_INVENTORY_CHANGE.INVENTORYSTATUSCODE2         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;        /* HAPI_INVENTORY_CHANGE.PRODUCTIONLOTIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity2;       /* HAPI_INVENTORY_CHANGE.PRODUCTIONLOTIDENTITY2       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;     /* HAPI_INVENTORY_CHANGE.PRODUCTIONSUBLOTIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSublotIdentity2;    /* HAPI_INVENTORY_CHANGE.PRODUCTIONSUBLOTIDENTITY2    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;         /* HAPI_INVENTORY_CHANGE.MARKETINGLOTIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity2;        /* HAPI_INVENTORY_CHANGE.MARKETINGLOTIDENTITY2        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string QualityLotIdentity;           /* HAPI_INVENTORY_CHANGE.QUALITYLOTIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string QualityLotIdentity2;          /* HAPI_INVENTORY_CHANGE.QUALITYLOTIDENTITY2          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;            /* HAPI_INVENTORY_CHANGE.WAREHOUSEIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;          /* HAPI_INVENTORY_CHANGE.CUSTOMERORDERNUMBER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;        /* HAPI_INVENTORY_CHANGE.CUSTOMERORDERSEQUENCE        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;    /* HAPI_INVENTORY_CHANGE.CUSTOMERORDERLINEPOSITION    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition; /* HAPI_INVENTORY_CHANGE.CUSTOMERORDERLINEKITPOSITION */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;    /* HAPI_INVENTORY_CHANGE.CUSTOMERORDERLINESEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReasonCode;                   /* HAPI_INVENTORY_CHANGE.REASONCODE                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FreeText;                     /* HAPI_INVENTORY_CHANGE.FREETEXT                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string EmployeeId;                   /* HAPI_INVENTORY_CHANGE.EMPLOYEEID                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime TimeStamp;                    /* HAPI_INVENTORY_CHANGE.TIMESTAMP                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ItemLoadIdentity;             /* HAPI_INVENTORY_CHANGE.ITEMLOADIDENTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OperationCode;                /* HAPI_INVENTORY_CHANGE.OPERATIONCODE                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryChangeCode;          /* HAPI_INVENTORY_CHANGE.INVENTORYCHANGECODE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryChangeText;          /* HAPI_INVENTORY_CHANGE.INVENTORYCHANGETEXT          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DespatchadviceIdentity;       /* HAPI_INVENTORY_CHANGE.DESPATCHADVICEIDENTITY       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;          /* HAPI_INVENTORY_CHANGE.PURCHASEORDERNUMBER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;        /* HAPI_INVENTORY_CHANGE.PURCHASEORDERSEQUENCE        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLinePosition;    /* HAPI_INVENTORY_CHANGE.PURCHASEORDERLINEPOSITION    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLineSequence;    /* HAPI_INVENTORY_CHANGE.PURCHASEORDERLINESEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorIdentity;               /* HAPI_INVENTORY_CHANGE.VENDORIDENTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;                /* HAPI_INVENTORY_CHANGE.OWNERIDENTITY                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity2;               /* HAPI_INVENTORY_CHANGE.OWNERIDENTITY2               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                /* HAPI_INVENTORY_CHANGE.PRODUCTNUMBER                */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PickReceiptHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                   /* .                                               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LastOndeparture;          /* HAPI_PICK_RECEIPT_HEAD.LASTONDEPARTURE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;      /* HAPI_PICK_RECEIPT_HEAD.CUSTOMERORDERNUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;    /* HAPI_PICK_RECEIPT_HEAD.CUSTOMERORDERSEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSubSequence; /* HAPI_PICK_RECEIPT_HEAD.CUSTOMERORDERSUBSEQUENCE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;        /* HAPI_PICK_RECEIPT_HEAD.WAREHOUSEIDENTITY        */


        public PickReceiptHeadPackingMaterialDoc[] aPickReceiptHeadPackingMaterialDocs;
        public PickReceiptLineDoc[] aPickReceiptLineDocs;
        public PickReceiptServiceDoc[] aPickReceiptServiceDocs;
        public PickReceiptTextDoc[] aPickReceiptTextDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PickReceiptHeadPackingMaterialDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                   /* .                                                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackingMaterialType;      /* HAPI_PICK_RECEIPT_HEAD_PM.PACKINGMATERIALTYPE      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Quantity;                 /* HAPI_PICK_RECEIPT_HEAD_PM.QUANTITY                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;      /* HAPI_PICK_RECEIPT_HEAD_PM.CUSTOMERORDERNUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;    /* HAPI_PICK_RECEIPT_HEAD_PM.CUSTOMERORDERSEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSubSequence; /* HAPI_PICK_RECEIPT_HEAD_PM.CUSTOMERORDERSUBSEQUENCE */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PickReceiptLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                       /* .                                                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition; /* HAPI_PICK_RECEIPT_LINE.CUSTOMERORDERLINEKITPOSITION */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;    /* HAPI_PICK_RECEIPT_LINE.CUSTOMERORDERLINESEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;                /* HAPI_PICK_RECEIPT_LINE.OWNERIDENTITY                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductIdentity;              /* HAPI_PICK_RECEIPT_LINE.PRODUCTIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;              /* HAPI_PICK_RECEIPT_LINE.PACKAGEIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PickQuantity;                 /* HAPI_PICK_RECEIPT_LINE.PICKQUANTITY                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MeasuredQty;                  /* HAPI_PICK_RECEIPT_LINE.MEASUREDQTY                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RestCode;                     /* HAPI_PICK_RECEIPT_LINE.RESTCODE                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DepartureIdentity;            /* HAPI_PICK_RECEIPT_LINE.DEPARTUREIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DepartureWeekday;             /* HAPI_PICK_RECEIPT_LINE.DEPARTUREWEEKDAY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;         /* HAPI_PICK_RECEIPT_LINE.MARKETINGLOTIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string QualityLotIdentity;           /* HAPI_PICK_RECEIPT_LINE.QUALITYLOTIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FreighterIdentity;            /* HAPI_PICK_RECEIPT_LINE.FREIGHTERIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ShipDate;                     /* HAPI_PICK_RECEIPT_LINE.SHIPDATE                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ConsignmentNote;              /* HAPI_PICK_RECEIPT_LINE.CONSIGNMENTNOTE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackingSlipIdentity;          /* HAPI_PICK_RECEIPT_LINE.PACKINGSLIPIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OrderedQuantity;              /* HAPI_PICK_RECEIPT_LINE.ORDEREDQUANTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double UnderQuantity;                /* HAPI_PICK_RECEIPT_LINE.UNDERQUANTITY                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OverQuantity;                 /* HAPI_PICK_RECEIPT_LINE.OVERQUANTITY                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;        /* HAPI_PICK_RECEIPT_LINE.PRODUCTIONLOTIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;     /* HAPI_PICK_RECEIPT_LINE.PRODUCTIONSUBLOTIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;          /* HAPI_PICK_RECEIPT_LINE.INVENTORYSTATUSCODE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SerialNumber;                 /* HAPI_PICK_RECEIPT_LINE.SERIALNUMBER                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;          /* HAPI_PICK_RECEIPT_LINE.CUSTOMERORDERNUMBER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;        /* HAPI_PICK_RECEIPT_LINE.CUSTOMERORDERSEQUENCE        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSubSequence;     /* HAPI_PICK_RECEIPT_LINE.CUSTOMERORDERSUBSEQUENCE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;    /* HAPI_PICK_RECEIPT_LINE.CUSTOMERORDERLINEPOSITION    */


        public PickReceiptLinePackingMaterialDoc[] aPickReceiptLinePackingMaterialDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PickReceiptLinePackingMaterialDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                       /* .                                                      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackingMaterialType;          /* HAPI_PICK_RECEIPT_LINE_PM.PACKINGMATERIALTYPE          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Quantity;                     /* HAPI_PICK_RECEIPT_LINE_PM.QUANTITY                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;          /* HAPI_PICK_RECEIPT_LINE_PM.CUSTOMERORDERNUMBER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;        /* HAPI_PICK_RECEIPT_LINE_PM.CUSTOMERORDERSEQUENCE        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSubSequence;     /* HAPI_PICK_RECEIPT_LINE_PM.CUSTOMERORDERSUBSEQUENCE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;    /* HAPI_PICK_RECEIPT_LINE_PM.CUSTOMERORDERLINEPOSITION    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition; /* HAPI_PICK_RECEIPT_LINE_PM.CUSTOMERORDERLINEKITPOSITION */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;    /* HAPI_PICK_RECEIPT_LINE_PM.CUSTOMERORDERLINESEQUENCE    */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PickReceiptServiceDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                   /* .                                                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;      /* HAPI_PICK_RECEIPT_SERVICE.CUSTOMERORDERNUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;    /* HAPI_PICK_RECEIPT_SERVICE.CUSTOMERORDERSEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSubSequence; /* HAPI_PICK_RECEIPT_SERVICE.CUSTOMERORDERSUBSEQUENCE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceQualifier;         /* HAPI_PICK_RECEIPT_SERVICE.SERVICEQUALIFIER         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceCode;              /* HAPI_PICK_RECEIPT_SERVICE.SERVICECODE              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double ServiceQty;               /* HAPI_PICK_RECEIPT_SERVICE.SERVICEQTY               */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class PickReceiptTextDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                   /* .                                               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;      /* HAPI_PICK_RECEIPT_TEXT.CUSTOMERORDERNUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;    /* HAPI_PICK_RECEIPT_TEXT.CUSTOMERORDERSEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSubSequence; /* HAPI_PICK_RECEIPT_TEXT.CUSTOMERORDERSUBSEQUENCE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TextFunction;             /* HAPI_PICK_RECEIPT_TEXT.TEXTFUNCTION             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Text;                     /* HAPI_PICK_RECEIPT_TEXT.TEXT                     */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ReturnedPackingMaterialHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;            /* .                                       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Rpmid;             /* HAPI_RETURNED_PM_HEAD.RPMID             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Customer_id;       /* HAPI_RETURNED_PM_HEAD.CUSTOMER_ID       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Referense;         /* HAPI_RETURNED_PM_HEAD.REFERENSE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ArrivalDateTime;   /* HAPI_RETURNED_PM_HEAD.ARRIVALDATETIME   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity; /* HAPI_RETURNED_PM_HEAD.WAREHOUSEIDENTITY */


        public ReturnedPackingMaterialLineDoc[] aReturnedPackingMaterialLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ReturnedPackingMaterialLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;          /* .                                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Rpmid;           /* HAPI_RETURNED_PM_LINE.RPMID           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Seqnum;          /* HAPI_RETURNED_PM_LINE.SEQNUM          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductIdentity; /* HAPI_RETURNED_PM_LINE.PRODUCTIDENTITY */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Quantity;        /* HAPI_RETURNED_PM_LINE.QUANTITY        */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ReturnReceiptHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                 /* .                                               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReturnOrderNumber;      /* HAPI_RETURN_RECEIPT_HEAD.RETURNORDERNUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ReturnOrderSequence;    /* HAPI_RETURN_RECEIPT_HEAD.RETURNORDERSEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ReturnOrderSubSequence; /* HAPI_RETURN_RECEIPT_HEAD.RETURNORDERSUBSEQUENCE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;      /* HAPI_RETURN_RECEIPT_HEAD.WAREHOUSEIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ShipDate;               /* HAPI_RETURN_RECEIPT_HEAD.SHIPDATE               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SpontaneousReturn;      /* HAPI_RETURN_RECEIPT_HEAD.SPONTANEOUSRETURN      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorIdentity;         /* HAPI_RETURN_RECEIPT_HEAD.VENDORIDENTITY         */


        public ReturnReceiptHeadPackingMaterialDoc[] aReturnReceiptHeadPackingMaterialDocs;
        public ReturnReceiptLineDoc[] aReturnReceiptLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ReturnReceiptHeadPackingMaterialDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                 /* .                                                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReturnOrderNumber;      /* HAPI_RETURN_RECEIPT_HEAD_PM.RETURNORDERNUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ReturnOrderSequence;    /* HAPI_RETURN_RECEIPT_HEAD_PM.RETURNORDERSEQUENCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ReturnOrderSubSequence; /* HAPI_RETURN_RECEIPT_HEAD_PM.RETURNORDERSUBSEQUENCE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ShipDate;               /* HAPI_RETURN_RECEIPT_HEAD_PM.SHIPDATE               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductIdentity;        /* HAPI_RETURN_RECEIPT_HEAD_PM.PRODUCTIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PickQuantity;           /* HAPI_RETURN_RECEIPT_HEAD_PM.PICKQUANTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SpontaneousReturn;      /* HAPI_RETURN_RECEIPT_HEAD_PM.SPONTANEOUSRETURN      */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ReturnReceiptLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                   /* .                                                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReturnOrderNumber;        /* HAPI_RETURN_RECEIPT_LINE.RETURNORDERNUMBER        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ReturnOrderSequence;      /* HAPI_RETURN_RECEIPT_LINE.RETURNORDERSEQUENCE      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ReturnOrderSubSequence;   /* HAPI_RETURN_RECEIPT_LINE.RETURNORDERSUBSEQUENCE   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ShipDate;                 /* HAPI_RETURN_RECEIPT_LINE.SHIPDATE                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ReturnOrderLinePosition;  /* HAPI_RETURN_RECEIPT_LINE.RETURNORDERLINEPOSITION  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ReturnOrderLineSequence;  /* HAPI_RETURN_RECEIPT_LINE.RETURNORDERLINESEQUENCE  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductIdentity;          /* HAPI_RETURN_RECEIPT_LINE.PRODUCTIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;          /* HAPI_RETURN_RECEIPT_LINE.PACKAGEIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;    /* HAPI_RETURN_RECEIPT_LINE.PRODUCTIONLOTIDENTITY    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity; /* HAPI_RETURN_RECEIPT_LINE.PRODUCTIONSUBLOTIDENTITY */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;     /* HAPI_RETURN_RECEIPT_LINE.MARKETINGLOTIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PickQuantity;             /* HAPI_RETURN_RECEIPT_LINE.PICKQUANTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Qtyback;                  /* HAPI_RETURN_RECEIPT_LINE.QTYBACK                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Qtycancel;                /* HAPI_RETURN_RECEIPT_LINE.QTYCANCEL                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double QtySurplusPick;           /* HAPI_RETURN_RECEIPT_LINE.QTYSURPLUSPICK           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;      /* HAPI_RETURN_RECEIPT_LINE.INVENTORYSTATUSCODE      */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ASNHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                       /* .                                                      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ASNIdentity;                  /* HAPI_SHIPMENT_REPORT_HEAD.ASNIDENTITY                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNSequenceNumber;            /* HAPI_SHIPMENT_REPORT_HEAD.ASNSEQUENCENUMBER            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;    /* HAPI_SHIPMENT_REPORT_HEAD.SHIPFROMPARTYNODEIDENTITY    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ASNLevel;                     /* HAPI_SHIPMENT_REPORT_HEAD.ASNLEVEL                     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ShipDateTime;                 /* HAPI_SHIPMENT_REPORT_HEAD.SHIPDATETIME                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime DocumentDateTime;             /* HAPI_SHIPMENT_REPORT_HEAD.DOCUMENTDATETIME             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime DeliveryWindowFirst;          /* HAPI_SHIPMENT_REPORT_HEAD.DELIVERYWINDOWFIRST          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime DeliveryWindowLast;           /* HAPI_SHIPMENT_REPORT_HEAD.DELIVERYWINDOWLAST           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ScheduledArrivalDateTime;     /* HAPI_SHIPMENT_REPORT_HEAD.SCHEDULEDARRIVALDATETIME     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;        /* HAPI_SHIPMENT_REPORT_HEAD.SHIPFROMPARTYIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyQualifier;       /* HAPI_SHIPMENT_REPORT_HEAD.SHIPFROMPARTYQUALIFIER       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyNodeIdentity;      /* HAPI_SHIPMENT_REPORT_HEAD.SHIPTOPARTYNODEIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyIdentity;          /* HAPI_SHIPMENT_REPORT_HEAD.SHIPTOPARTYIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyQualifier;         /* HAPI_SHIPMENT_REPORT_HEAD.SHIPTOPARTYQUALIFIER         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ForwarderIdentity;            /* HAPI_SHIPMENT_REPORT_HEAD.FORWARDERIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                 /* HAPI_SHIPMENT_REPORT_HEAD.INSTRUCTIONS                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int NumberOfLoadCarriers;         /* HAPI_SHIPMENT_REPORT_HEAD.NUMBEROFLOADCARRIERS         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VehicleIdentity;              /* HAPI_SHIPMENT_REPORT_HEAD.VEHICLEIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double EstimatedVolume;              /* HAPI_SHIPMENT_REPORT_HEAD.ESTIMATEDVOLUME              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VolumeUOMIdentity;            /* HAPI_SHIPMENT_REPORT_HEAD.VOLUMEUOMIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BillOfLadingNumber;           /* HAPI_SHIPMENT_REPORT_HEAD.BILLOFLADINGNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackingSlipNumber;            /* HAPI_SHIPMENT_REPORT_HEAD.PACKINGSLIPNUMBER            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShippedFromWarehouseIdentity; /* HAPI_SHIPMENT_REPORT_HEAD.SHIPPEDFROMWAREHOUSEIDENTITY */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShippedOnDepartureIdentity;   /* HAPI_SHIPMENT_REPORT_HEAD.SHIPPEDONDEPARTUREIDENTITY   */


        public ASNLoadCarrierDoc[] aASNLoadCarrierDocs;
        public ASNLineDoc[] aASNLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ASNLoadCarrierDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                     /* .                                                       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VolumeUOMIdentity;          /* HAPI_SHIPMENT_REPORT_CARRIER.VOLUMEUOMIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double TotalHeight;                /* HAPI_SHIPMENT_REPORT_CARRIER.TOTALHEIGHT                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string HeightUOMIdentity;          /* HAPI_SHIPMENT_REPORT_CARRIER.HEIGHTUOMIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ASNIdentity;                /* HAPI_SHIPMENT_REPORT_CARRIER.ASNIDENTITY                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNSequenceNumber;          /* HAPI_SHIPMENT_REPORT_CARRIER.ASNSEQUENCENUMBER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;  /* HAPI_SHIPMENT_REPORT_CARRIER.SHIPFROMPARTYNODEIDENTITY  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierIdentity;        /* HAPI_SHIPMENT_REPORT_CARRIER.LOADCARRIERIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierQualifier;       /* HAPI_SHIPMENT_REPORT_CARRIER.LOADCARRIERQUALIFIER       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierType;            /* HAPI_SHIPMENT_REPORT_CARRIER.LOADCARRIERTYPE            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ExternalLoadCarrierType;    /* HAPI_SHIPMENT_REPORT_CARRIER.EXTERNALLOADCARRIERTYPE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ParentLoadCarrierIdentity;  /* HAPI_SHIPMENT_REPORT_CARRIER.PARENTLOADCARRIERIDENTITY  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductTransportIdentity;   /* HAPI_SHIPMENT_REPORT_CARRIER.PRODUCTTRANSPORTIDENTITY   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;      /* HAPI_SHIPMENT_REPORT_CARRIER.SHIPFROMPARTYIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyNodeIdentity;    /* HAPI_SHIPMENT_REPORT_CARRIER.SHIPTOPARTYNODEIDENTITY    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyIdentity;        /* HAPI_SHIPMENT_REPORT_CARRIER.SHIPTOPARTYIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyQualifier;       /* HAPI_SHIPMENT_REPORT_CARRIER.SHIPTOPARTYQUALIFIER       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToCustomerNodeIdentity; /* HAPI_SHIPMENT_REPORT_CARRIER.SHIPTOCUSTOMERNODEIDENTITY */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerIdentity;     /* HAPI_SHIPMENT_REPORT_CARRIER.SHIPTOCUSTOMERIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerQualifier;    /* HAPI_SHIPMENT_REPORT_CARRIER.SHIPTOCUSTOMERQUALIFIER    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;               /* HAPI_SHIPMENT_REPORT_CARRIER.INSTRUCTIONS               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double TotalWeight;                /* HAPI_SHIPMENT_REPORT_CARRIER.TOTALWEIGHT                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WeightUOMIdentity;          /* HAPI_SHIPMENT_REPORT_CARRIER.WEIGHTUOMIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double TotalVolume;                /* HAPI_SHIPMENT_REPORT_CARRIER.TOTALVOLUME                */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ASNLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineSequence;     /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERORDERLINESEQUENCE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLineKitPosition;  /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERORDERLINEKITPOSITION  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalPurchaseOrderNumber;   /* HAPI_SHIPMENT_REPORT_LINE.ORIGINALPURCHASEORDERNUMBER   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int OriginalPurchaseOrderSequence; /* HAPI_SHIPMENT_REPORT_LINE.ORIGINALPURCHASEORDERSEQUENCE */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double OriginalPurchaseOrderLinePos;  /* HAPI_SHIPMENT_REPORT_LINE.ORIGINALPURCHASEORDERLINEPOS  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int OriginalPurchaseOrderLineSeq;  /* HAPI_SHIPMENT_REPORT_LINE.ORIGINALPURCHASEORDERLINESEQ  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OriginalCustomerReference;     /* HAPI_SHIPMENT_REPORT_LINE.ORIGINALCUSTOMERREFERENCE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;           /* HAPI_SHIPMENT_REPORT_LINE.INVENTORYSTATUSCODE           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InventoryStatusDays;           /* HAPI_SHIPMENT_REPORT_LINE.INVENTORYSTATUSDAYS           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventorystatusKey;            /* HAPI_SHIPMENT_REPORT_LINE.INVENTORYSTATUSKEY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventorystatusText;           /* HAPI_SHIPMENT_REPORT_LINE.INVENTORYSTATUSTEXT           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime InventorystatusAlarmDate;      /* HAPI_SHIPMENT_REPORT_LINE.INVENTORYSTATUSALARMDATE      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Instructions;                  /* HAPI_SHIPMENT_REPORT_LINE.INSTRUCTIONS                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PredefinedItemLoadIdentity;    /* HAPI_SHIPMENT_REPORT_LINE.PREDEFINEDITEMLOADIDENTITY    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumberShipFromPartner;  /* HAPI_SHIPMENT_REPORT_LINE.PRODUCTNUMBERSHIPFROMPARTNER  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumberShipToPartner;    /* HAPI_SHIPMENT_REPORT_LINE.PRODUCTNUMBERSHIPTOPARTNER    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string GlobalProductNumber;           /* HAPI_SHIPMENT_REPORT_LINE.GLOBALPRODUCTNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AdditionalPackingMaterial;     /* HAPI_SHIPMENT_REPORT_LINE.ADDITIONALPACKINGMATERIAL     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderType;             /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERORDERTYPE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;           /* HAPI_SHIPMENT_REPORT_LINE.PURCHASEORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;         /* HAPI_SHIPMENT_REPORT_LINE.PURCHASEORDERSEQUENCE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLinePos;          /* HAPI_SHIPMENT_REPORT_LINE.PURCHASEORDERLINEPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLineSeq;          /* HAPI_SHIPMENT_REPORT_LINE.PURCHASEORDERLINESEQ          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StockedProductNumber;          /* HAPI_SHIPMENT_REPORT_LINE.STOCKEDPRODUCTNUMBER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string GlobalStockedProductNumber;    /* HAPI_SHIPMENT_REPORT_LINE.GLOBALSTOCKEDPRODUCTNUMBER    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyIdentity;             /* HAPI_SHIPMENT_REPORT_LINE.FROMPARTYIDENTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string FromPartyQualifier;            /* HAPI_SHIPMENT_REPORT_LINE.FROMPARTYQUALIFIER            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERRETURNORDERNUMBER     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERRETURNORDERSEQUENCE   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERRETURNORDERLINEPOS    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERRETURNORDERLINEKITPOS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERRETURNORDERLINESEQ    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ActionCode;                    /* HAPI_SHIPMENT_REPORT_LINE.ACTIONCODE                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ActionCodeRequirement;         /* HAPI_SHIPMENT_REPORT_LINE.ACTIONCODEREQUIREMENT         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReasonCode;                    /* HAPI_SHIPMENT_REPORT_LINE.REASONCODE                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ReasonText;                    /* HAPI_SHIPMENT_REPORT_LINE.REASONTEXT                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoVendorIdentity;          /* HAPI_SHIPMENT_REPORT_LINE.SHIPTOVENDORIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoVendorQualifier;         /* HAPI_SHIPMENT_REPORT_LINE.SHIPTOVENDORQUALIFIER         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double DiscrepancyQuantity;           /* HAPI_SHIPMENT_REPORT_LINE.DISCREPANCYQUANTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DiscrepancyCode;               /* HAPI_SHIPMENT_REPORT_LINE.DISCREPANCYCODE               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DiscrepancyText;               /* HAPI_SHIPMENT_REPORT_LINE.DISCREPANCYTEXT               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double QuantityUpperTolerance;        /* HAPI_SHIPMENT_REPORT_LINE.QUANTITYUPPERTOLERANCE        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureLowerTolerance;    /* HAPI_SHIPMENT_REPORT_LINE.CATCHMEASURELOWERTOLERANCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double CatchMeasureUpperTolerance;    /* HAPI_SHIPMENT_REPORT_LINE.CATCHMEASUREUPPERTOLERANCE    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ASNIdentity;                   /* HAPI_SHIPMENT_REPORT_LINE.ASNIDENTITY                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNSequenceNumber;             /* HAPI_SHIPMENT_REPORT_LINE.ASNSEQUENCENUMBER             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;     /* HAPI_SHIPMENT_REPORT_LINE.SHIPFROMPARTYNODEIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNLineNumber;                 /* HAPI_SHIPMENT_REPORT_LINE.ASNLINENUMBER                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int ASNLineSequenceNumber;         /* HAPI_SHIPMENT_REPORT_LINE.ASNLINESEQUENCENUMBER         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierIdentity;           /* HAPI_SHIPMENT_REPORT_LINE.LOADCARRIERIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;         /* HAPI_SHIPMENT_REPORT_LINE.SHIPFROMPARTYIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyNodeIdentity;       /* HAPI_SHIPMENT_REPORT_LINE.SHIPTOPARTYNODEIDENTITY       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyIdentity;           /* HAPI_SHIPMENT_REPORT_LINE.SHIPTOPARTYIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyQualifier;          /* HAPI_SHIPMENT_REPORT_LINE.SHIPTOPARTYQUALIFIER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToCustomerNodeIdentity;    /* HAPI_SHIPMENT_REPORT_LINE.SHIPTOCUSTOMERNODEIDENTITY    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerIdentity;        /* HAPI_SHIPMENT_REPORT_LINE.SHIPTOCUSTOMERIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoCustomerQualifier;       /* HAPI_SHIPMENT_REPORT_LINE.SHIPTOCUSTOMERQUALIFIER       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerIdentity;        /* HAPI_SHIPMENT_REPORT_LINE.SELLTOCUSTOMERIDENTITY        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SelltoCustomerQualifier;       /* HAPI_SHIPMENT_REPORT_LINE.SELLTOCUSTOMERQUALIFIER       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentity;                 /* HAPI_SHIPMENT_REPORT_LINE.OWNERIDENTITY                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string OwnerIdentityAtShipToCustomer; /* HAPI_SHIPMENT_REPORT_LINE.OWNERIDENTITYATSHIPTOCUSTOMER */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorIdentity;                /* HAPI_SHIPMENT_REPORT_LINE.VENDORIDENTITY                */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorPartyNodeIdentity;       /* HAPI_SHIPMENT_REPORT_LINE.VENDORPARTYNODEIDENTITY       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                 /* HAPI_SHIPMENT_REPORT_LINE.PRODUCTNUMBER                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductDescription;            /* HAPI_SHIPMENT_REPORT_LINE.PRODUCTDESCRIPTION            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumberType;             /* HAPI_SHIPMENT_REPORT_LINE.PRODUCTNUMBERTYPE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AlternativeProductNumber;      /* HAPI_SHIPMENT_REPORT_LINE.ALTERNATIVEPRODUCTNUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AlternativeProductDescription; /* HAPI_SHIPMENT_REPORT_LINE.ALTERNATIVEPRODUCTDESCRIPTION */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ProductDate;                   /* HAPI_SHIPMENT_REPORT_LINE.PRODUCTDATE                   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ExpiryDate;                    /* HAPI_SHIPMENT_REPORT_LINE.EXPIRYDATE                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ManufacturingDate;             /* HAPI_SHIPMENT_REPORT_LINE.MANUFACTURINGDATE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VendorProductNumber;           /* HAPI_SHIPMENT_REPORT_LINE.VENDORPRODUCTNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double PurchasePrice;                 /* HAPI_SHIPMENT_REPORT_LINE.PURCHASEPRICE                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageIdentity;               /* HAPI_SHIPMENT_REPORT_LINE.PACKAGEIDENTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;         /* HAPI_SHIPMENT_REPORT_LINE.PRODUCTIONLOTIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;      /* HAPI_SHIPMENT_REPORT_LINE.PRODUCTIONSUBLOTIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ManufacturingUnit;             /* HAPI_SHIPMENT_REPORT_LINE.MANUFACTURINGUNIT             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MarketingLotIdentity;          /* HAPI_SHIPMENT_REPORT_LINE.MARKETINGLOTIDENTITY          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SerialNumber;                  /* HAPI_SHIPMENT_REPORT_LINE.SERIALNUMBER                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StorageLot;                    /* HAPI_SHIPMENT_REPORT_LINE.STORAGELOT                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double ShippedQuantity;               /* HAPI_SHIPMENT_REPORT_LINE.SHIPPEDQUANTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MeasuredQuantity;              /* HAPI_SHIPMENT_REPORT_LINE.MEASUREDQUANTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MeasureQualifier;              /* HAPI_SHIPMENT_REPORT_LINE.MEASUREQUALIFIER              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Volume;                        /* HAPI_SHIPMENT_REPORT_LINE.VOLUME                        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string VolumeUOMIdentity;             /* HAPI_SHIPMENT_REPORT_LINE.VOLUMEUOMIDENTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double Weight;                        /* HAPI_SHIPMENT_REPORT_LINE.WEIGHT                        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WeightUOMIdentity;             /* HAPI_SHIPMENT_REPORT_LINE.WEIGHTUOMIDENTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderNumber;           /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderSequence;         /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERORDERSEQUENCE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerOrderLinePosition;     /* HAPI_SHIPMENT_REPORT_LINE.CUSTOMERORDERLINEPOSITION     */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ConfirmationOfReceiptHeadDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AcknowledgeInboundAsnIdentity; /* HAPI_CONF_OF_RECEIPT_HEAD.ACKNOWLEDGEINBOUNDASNIDENTITY */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ArrivalDateTime;               /* HAPI_CONF_OF_RECEIPT_HEAD.ARRIVALDATETIME               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyNodeIdentity;       /* HAPI_CONF_OF_RECEIPT_HEAD.SHIPTOPARTYNODEIDENTITY       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyIdentity;           /* HAPI_CONF_OF_RECEIPT_HEAD.SHIPTOPARTYIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyQualifier;          /* HAPI_CONF_OF_RECEIPT_HEAD.SHIPTOPARTYQUALIFIER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;     /* HAPI_CONF_OF_RECEIPT_HEAD.SHIPFROMPARTYNODEIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;         /* HAPI_CONF_OF_RECEIPT_HEAD.SHIPFROMPARTYIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyQualifier;        /* HAPI_CONF_OF_RECEIPT_HEAD.SHIPFROMPARTYQUALIFIER        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InboundAsnIdentity;            /* HAPI_CONF_OF_RECEIPT_HEAD.INBOUNDASNIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InboundAsnSequenceNumber;      /* HAPI_CONF_OF_RECEIPT_HEAD.INBOUNDASNSEQUENCENUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AcknowledgeInboundAsnType;     /* HAPI_CONF_OF_RECEIPT_HEAD.ACKNOWLEDGEINBOUNDASNTYPE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ForwarderIdentity;             /* HAPI_CONF_OF_RECEIPT_HEAD.FORWARDERIDENTITY             */


        public ConfirmationOfReceiptLoadCarrierDoc[] aConfirmationOfReceiptLoadCarrierDocs;
        public ConfirmationOfReceiptLineDoc[] aConfirmationOfReceiptLineDocs;
    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ConfirmationOfReceiptLoadCarrierDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AcknowledgeInboundAsnIdentity; /* HAPI_CONF_OF_RECEIPT_CARRIER.ACKNOWLEDGEINBOUNDASNIDENTITY */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierIdentity;           /* HAPI_CONF_OF_RECEIPT_CARRIER.LOADCARRIERIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierQualifier;          /* HAPI_CONF_OF_RECEIPT_CARRIER.LOADCARRIERQUALIFIER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ArrivalDateTime;               /* HAPI_CONF_OF_RECEIPT_CARRIER.ARRIVALDATETIME               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipToPartyNodeIdentity;       /* HAPI_CONF_OF_RECEIPT_CARRIER.SHIPTOPARTYNODEIDENTITY       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyIdentity;           /* HAPI_CONF_OF_RECEIPT_CARRIER.SHIPTOPARTYIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShiptoPartyQualifier;          /* HAPI_CONF_OF_RECEIPT_CARRIER.SHIPTOPARTYQUALIFIER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;     /* HAPI_CONF_OF_RECEIPT_CARRIER.SHIPFROMPARTYNODEIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;         /* HAPI_CONF_OF_RECEIPT_CARRIER.SHIPFROMPARTYIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyQualifier;        /* HAPI_CONF_OF_RECEIPT_CARRIER.SHIPFROMPARTYQUALIFIER        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InboundAsnIdentity;            /* HAPI_CONF_OF_RECEIPT_CARRIER.INBOUNDASNIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InboundAsnSequenceNumber;      /* HAPI_CONF_OF_RECEIPT_CARRIER.INBOUNDASNSEQUENCENUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryIdentity;              /* HAPI_CONF_OF_RECEIPT_CARRIER.DELIVERYIDENTITY              */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class ConfirmationOfReceiptLineDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                       */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AcknowledgeInboundAsnIdentity; /* HAPI_CONF_OF_RECEIPT_LINE.ACKNOWLEDGEINBOUNDASNIDENTITY */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int AcknowledgeInboundAsnLinenum;  /* HAPI_CONF_OF_RECEIPT_LINE.ACKNOWLEDGEINBOUNDASNLINENUM  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ArrivalDateTime;               /* HAPI_CONF_OF_RECEIPT_LINE.ARRIVALDATETIME               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyNodeIdentity;     /* HAPI_CONF_OF_RECEIPT_LINE.SHIPFROMPARTYNODEIDENTITY     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyIdentity;         /* HAPI_CONF_OF_RECEIPT_LINE.SHIPFROMPARTYIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipFromPartyQualifier;        /* HAPI_CONF_OF_RECEIPT_LINE.SHIPFROMPARTYQUALIFIER        */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InboundAsnIdentity;            /* HAPI_CONF_OF_RECEIPT_LINE.INBOUNDASNIDENTITY            */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InboundAsnSequenceNumber;      /* HAPI_CONF_OF_RECEIPT_LINE.INBOUNDASNSEQUENCENUMBER      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InboundAsnLineNumber;          /* HAPI_CONF_OF_RECEIPT_LINE.INBOUNDASNLINENUMBER          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int InboundAsnLineSequenceNumber;  /* HAPI_CONF_OF_RECEIPT_LINE.INBOUNDASNLINESEQUENCENUMBER  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductNumber;                 /* HAPI_CONF_OF_RECEIPT_LINE.PRODUCTNUMBER                 */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double AsnLineQuantity;               /* HAPI_CONF_OF_RECEIPT_LINE.ASNLINEQUANTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double ArrivedQuantity;               /* HAPI_CONF_OF_RECEIPT_LINE.ARRIVEDQUANTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double ReceiptQuantity;               /* HAPI_CONF_OF_RECEIPT_LINE.RECEIPTQUANTITY               */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionLotIdentity;         /* HAPI_CONF_OF_RECEIPT_LINE.PRODUCTIONLOTIDENTITY         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductionSubLotIdentity;      /* HAPI_CONF_OF_RECEIPT_LINE.PRODUCTIONSUBLOTIDENTITY      */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SerialNumber;                  /* HAPI_CONF_OF_RECEIPT_LINE.SERIALNUMBER                  */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int DeliveryIdentity;              /* HAPI_CONF_OF_RECEIPT_LINE.DELIVERYIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LoadCarrierIdentity;           /* HAPI_CONF_OF_RECEIPT_LINE.LOADCARRIERIDENTITY           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;           /* HAPI_CONF_OF_RECEIPT_LINE.PURCHASEORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;         /* HAPI_CONF_OF_RECEIPT_LINE.PURCHASEORDERSEQUENCE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLinePos;          /* HAPI_CONF_OF_RECEIPT_LINE.PURCHASEORDERLINEPOS          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLineSeq;          /* HAPI_CONF_OF_RECEIPT_LINE.PURCHASEORDERLINESEQ          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerOrderType;             /* HAPI_CONF_OF_RECEIPT_LINE.CUSTOMERORDERTYPE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ExpiryDate;                    /* HAPI_CONF_OF_RECEIPT_LINE.EXPIRYDATE                    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public dateTime ManufacturingDate;             /* HAPI_CONF_OF_RECEIPT_LINE.MANUFACTURINGDATE             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string InventoryStatusCode;           /* HAPI_CONF_OF_RECEIPT_LINE.INVENTORYSTATUSCODE           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @double MeasuredQuantity;              /* HAPI_CONF_OF_RECEIPT_LINE.MEASUREDQUANTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MeasureQualifier;              /* HAPI_CONF_OF_RECEIPT_LINE.MEASUREQUALIFIER              */


    }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://im.se/wms/webservices/")]
    public class InboundOrderCompletedDoc
    {
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = false)]
        public string OPCODE;                        /* .                                                          */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string WarehouseIdentity;             /* HAPI_INBOUND_ORDER_COMPLETED.WAREHOUSEIDENTITY             */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string EmployeeIdentity;              /* HAPI_INBOUND_ORDER_COMPLETED.EMPLOYEEIDENTITY              */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PurchaseOrderNumber;           /* HAPI_INBOUND_ORDER_COMPLETED.PURCHASEORDERNUMBER           */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderSequence;         /* HAPI_INBOUND_ORDER_COMPLETED.PURCHASEORDERSEQUENCE         */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLinePosition;     /* HAPI_INBOUND_ORDER_COMPLETED.PURCHASEORDERLINEPOSITION     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int PurchaseOrderLineSequence;     /* HAPI_INBOUND_ORDER_COMPLETED.PURCHASEORDERLINESEQUENCE     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CustomerReturnOrderNumber;     /* HAPI_INBOUND_ORDER_COMPLETED.CUSTOMERRETURNORDERNUMBER     */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderSequence;   /* HAPI_INBOUND_ORDER_COMPLETED.CUSTOMERRETURNORDERSEQUENCE   */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLinePos;    /* HAPI_INBOUND_ORDER_COMPLETED.CUSTOMERRETURNORDERLINEPOS    */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineKitPos; /* HAPI_INBOUND_ORDER_COMPLETED.CUSTOMERRETURNORDERLINEKITPOS */

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public @int CustomerReturnOrderLineSeq;    /* HAPI_INBOUND_ORDER_COMPLETED.CUSTOMERRETURNORDERLINESEQ    */

    }
}
