//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imi.SupplyChain.UX.Modules.Warehouse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imi.SupplyChain.UX.Modules.Warehouse.LocalResources", typeof(LocalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a default Client and/or Warehouse..
        /// </summary>
        public static string ChangeUserSettings_Caption {
            get {
                return ResourceManager.GetString("ChangeUserSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        public static string ChangeUserSettings_Client {
            get {
                return ResourceManager.GetString("ChangeUserSettings_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will discard any unsaved changes in the following dialogs:
        ///
        ///{0}
        ///
        ///Are you sure you want to continue?.
        /// </summary>
        public static string ChangeUserSettings_CloseAll {
            get {
                return ResourceManager.GetString("ChangeUserSettings_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last logged on:.
        /// </summary>
        public static string ChangeUserSettings_LastLogon {
            get {
                return ResourceManager.GetString("ChangeUserSettings_LastLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t, no dialog can be started. Please use the Change User Settings dialog to make a selection..
        /// </summary>
        public static string ChangeUserSettings_Message {
            get {
                return ResourceManager.GetString("ChangeUserSettings_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Settings.
        /// </summary>
        public static string ChangeUserSettings_Title {
            get {
                return ResourceManager.GetString("ChangeUserSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse:.
        /// </summary>
        public static string ChangeUserSettings_Warehouse {
            get {
                return ResourceManager.GetString("ChangeUserSettings_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Diagnostics_Close {
            get {
                return ResourceManager.GetString("Diagnostics_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Start to enable database tracing.
        /// </summary>
        public static string Diagnostics_Database_Description {
            get {
                return ResourceManager.GetString("Diagnostics_Database_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database tracing.
        /// </summary>
        public static string Diagnostics_Database_Title {
            get {
                return ResourceManager.GetString("Diagnostics_Database_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory:.
        /// </summary>
        public static string Diagnostics_Directory_Caption {
            get {
                return ResourceManager.GetString("Diagnostics_Directory_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Start to enable interface tracing.
        /// </summary>
        public static string Diagnostics_Interface_Description {
            get {
                return ResourceManager.GetString("Diagnostics_Interface_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (s):.
        /// </summary>
        public static string Diagnostics_Interface_Duration_Caption {
            get {
                return ResourceManager.GetString("Diagnostics_Interface_Duration_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Until:.
        /// </summary>
        public static string Diagnostics_Interface_Running_Caption {
            get {
                return ResourceManager.GetString("Diagnostics_Interface_Running_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface tracing.
        /// </summary>
        public static string Diagnostics_Interface_Title {
            get {
                return ResourceManager.GetString("Diagnostics_Interface_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name:.
        /// </summary>
        public static string Diagnostics_ServerName_Caption {
            get {
                return ResourceManager.GetString("Diagnostics_ServerName_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Diagnostics_Start {
            get {
                return ResourceManager.GetString("Diagnostics_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Diagnostics_Stop {
            get {
                return ResourceManager.GetString("Diagnostics_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Diagnostics.
        /// </summary>
        public static string Diagnostics_Title {
            get {
                return ResourceManager.GetString("Diagnostics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace File Location.
        /// </summary>
        public static string Diagnostics_TraceFile_Title {
            get {
                return ResourceManager.GetString("Diagnostics_TraceFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string Module_Title {
            get {
                return ResourceManager.GetString("Module_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) {1} / ({2}) {3}.
        /// </summary>
        public static string STATUSBAR_WH_CLIENT {
            get {
                return ResourceManager.GetString("STATUSBAR_WH_CLIENT", resourceCulture);
            }
        }
    }
}
