//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imi.SupplyChain.UX.Modules.Warehouse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imi.SupplyChain.UX.Modules.Warehouse.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Queue.
        /// </summary>
        public static string str_019e4419_bd2e_4741_b14e_876da7990c84_Caption {
            get {
                return ResourceManager.GetString("str_019e4419_bd2e_4741_b14e_876da7990c84_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slotting Input.
        /// </summary>
        public static string str_036ed5f2_ea0f_4595_bdf7_92397846a006_Caption {
            get {
                return ResourceManager.GetString("str_036ed5f2_ea0f_4595_bdf7_92397846a006_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Change History.
        /// </summary>
        public static string str_04ce5ab7_ece8_4cec_8724_0b8298f5c1e0_Caption {
            get {
                return ResourceManager.GetString("str_04ce5ab7_ece8_4cec_8724_0b8298f5c1e0_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string str_04f4e174_242c_473b_bcfb_a68b9d21932a_Caption {
            get {
                return ResourceManager.GetString("str_04f4e174_242c_473b_bcfb_a68b9d21932a_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string str_058208f8_f828_4f98_8a32_e1fe6c372c61_Caption {
            get {
                return ResourceManager.GetString("str_058208f8_f828_4f98_8a32_e1fe6c372c61_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Location.
        /// </summary>
        public static string str_06a70084_b48b_4afc_bf5c_2a1f0a14c790_Caption {
            get {
                return ResourceManager.GetString("str_06a70084_b48b_4afc_bf5c_2a1f0a14c790_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Replenishment Order.
        /// </summary>
        public static string str_078ffc1f_46cd_4ebb_a6dd_57ca3842625e_Caption {
            get {
                return ResourceManager.GetString("str_078ffc1f_46cd_4ebb_a6dd_57ca3842625e_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Truck.
        /// </summary>
        public static string str_09f4a0c7_1409_46ac_9ba7_f994b34d8793_Caption {
            get {
                return ResourceManager.GetString("str_09f4a0c7_1409_46ac_9ba7_f994b34d8793_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Audit Order.
        /// </summary>
        public static string str_0c461be0_29f1_438b_a808_dacf37cfd34f_Caption {
            get {
                return ResourceManager.GetString("str_0c461be0_29f1_438b_a808_dacf37cfd34f_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Load Carrier History.
        /// </summary>
        public static string str_0fba71c5_d33b_4ff3_b72e_034b9c9b19b4_Caption {
            get {
                return ResourceManager.GetString("str_0fba71c5_d33b_4ff3_b72e_034b9c9b19b4_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string str_1010d265_e93c_428a_a81b_02f4cac295e2_Caption {
            get {
                return ResourceManager.GetString("str_1010d265_e93c_428a_a81b_02f4cac295e2_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string str_101bad4c_78fd_4967_822c_1693bac9196a_Caption {
            get {
                return ResourceManager.GetString("str_101bad4c_78fd_4967_822c_1693bac9196a_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Stock Group.
        /// </summary>
        public static string str_11426b5f_1c5e_450c_96c1_b1cf30457097_Caption {
            get {
                return ResourceManager.GetString("str_11426b5f_1c5e_450c_96c1_b1cf30457097_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string str_11655214_4f86_448c_be03_becfc2cedcdf_Caption {
            get {
                return ResourceManager.GetString("str_11655214_4f86_448c_be03_becfc2cedcdf_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string str_1768e807_509c_4b70_801b_cf1dcb2ab7e7_Caption {
            get {
                return ResourceManager.GetString("str_1768e807_509c_4b70_801b_cf1dcb2ab7e7_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Order.
        /// </summary>
        public static string str_1ec23f74_b068_43e4_85ad_f4c843e8ad16_Caption {
            get {
                return ResourceManager.GetString("str_1ec23f74_b068_43e4_85ad_f4c843e8ad16_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Pick.
        /// </summary>
        public static string str_1f08e2fd_21ce_4d55_b300_8a03094572d9_Caption {
            get {
                return ResourceManager.GetString("str_1f08e2fd_21ce_4d55_b300_8a03094572d9_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string str_1fc32bd4_6111_4779_b4fe_e6ee00ba3380_Caption {
            get {
                return ResourceManager.GetString("str_1fc32bd4_6111_4779_b4fe_e6ee00ba3380_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string str_214858f4_d3da_431d_b259_c8e12686ce29_Caption {
            get {
                return ResourceManager.GetString("str_214858f4_d3da_431d_b259_c8e12686ce29_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Inventory Audit.
        /// </summary>
        public static string str_23011430_b394_49fc_be46_0f857f467752_Caption {
            get {
                return ResourceManager.GetString("str_23011430_b394_49fc_be46_0f857f467752_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Warehouse Rule.
        /// </summary>
        public static string str_233d84ad_770e_4d26_9998_198cf1c306dc_Caption {
            get {
                return ResourceManager.GetString("str_233d84ad_770e_4d26_9998_198cf1c306dc_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undestined Load Carriers.
        /// </summary>
        public static string str_2559f6b7_df3d_45fd_bf0f_9e6bece9cc32_Caption {
            get {
                return ResourceManager.GetString("str_2559f6b7_df3d_45fd_bf0f_9e6bece9cc32_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment.
        /// </summary>
        public static string str_2632d2e0_b813_414e_b73a_d5dd17ba59e0_Caption {
            get {
                return ResourceManager.GetString("str_2632d2e0_b813_414e_b73a_d5dd17ba59e0_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Wave.
        /// </summary>
        public static string str_278b380b_48c7_4aab_aaec_45e2d22ef3c5_Caption {
            get {
                return ResourceManager.GetString("str_278b380b_48c7_4aab_aaec_45e2d22ef3c5_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string str_3055986f_83c4_4191_901f_dda9d4b40d88_Caption {
            get {
                return ResourceManager.GetString("str_3055986f_83c4_4191_901f_dda9d4b40d88_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Packing Material.
        /// </summary>
        public static string str_306e3351_9b4f_4762_8fb8_9e13b4d53400_Caption {
            get {
                return ResourceManager.GetString("str_306e3351_9b4f_4762_8fb8_9e13b4d53400_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Wave History.
        /// </summary>
        public static string str_316ee39c_130a_4ad2_a9cc_da6e045833c4_Caption {
            get {
                return ResourceManager.GetString("str_316ee39c_130a_4ad2_a9cc_da6e045833c4_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string str_324b0a21_cf08_491e_b651_2450fe15d598_Caption {
            get {
                return ResourceManager.GetString("str_324b0a21_cf08_491e_b651_2450fe15d598_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Outline.
        /// </summary>
        public static string str_353ea57b_4cf4_478d_8086_879b4e2ac76f_Caption {
            get {
                return ResourceManager.GetString("str_353ea57b_4cf4_478d_8086_879b4e2ac76f_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Audit.
        /// </summary>
        public static string str_35abffc0_c43f_4c8e_a5c8_2937a77ae33e_Caption {
            get {
                return ResourceManager.GetString("str_35abffc0_c43f_4c8e_a5c8_2937a77ae33e_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure System.
        /// </summary>
        public static string str_362e23a0_8574_4587_a5d6_583129f2afc2_Caption {
            get {
                return ResourceManager.GetString("str_362e23a0_8574_4587_a5d6_583129f2afc2_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string str_369f79da_d98d_4fa2_a0e5_b23c533c28bd_Caption {
            get {
                return ResourceManager.GetString("str_369f79da_d98d_4fa2_a0e5_b23c533c28bd_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Replenishment from Item Load.
        /// </summary>
        public static string str_37a4dbdd_0070_4231_8193_7b46a6e6662f_Caption {
            get {
                return ResourceManager.GetString("str_37a4dbdd_0070_4231_8193_7b46a6e6662f_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Material.
        /// </summary>
        public static string str_3d74997f_1047_4a2b_a612_d3bf0637e378_Caption {
            get {
                return ResourceManager.GetString("str_3d74997f_1047_4a2b_a612_d3bf0637e378_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Load History.
        /// </summary>
        public static string str_3f2f5631_0f74_48cd_a249_bfd400f04585_Caption {
            get {
                return ResourceManager.GetString("str_3f2f5631_0f74_48cd_a249_bfd400f04585_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Truck Type.
        /// </summary>
        public static string str_440ae6a2_ad0f_41ce_bbc8_161dd46fd73d_Caption {
            get {
                return ResourceManager.GetString("str_440ae6a2_ad0f_41ce_bbc8_161dd46fd73d_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string str_47ab8696_a834_41f3_8b72_1e473cfabcaf_Caption {
            get {
                return ResourceManager.GetString("str_47ab8696_a834_41f3_8b72_1e473cfabcaf_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Order Type.
        /// </summary>
        public static string str_4a696f00_592b_4674_b9a7_283d1d727485_Caption {
            get {
                return ResourceManager.GetString("str_4a696f00_592b_4674_b9a7_283d1d727485_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slotting.
        /// </summary>
        public static string str_4cf4aa29_2e31_49f4_9171_4f58a768636e_Caption {
            get {
                return ResourceManager.GetString("str_4cf4aa29_2e31_49f4_9171_4f58a768636e_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Carrier Group.
        /// </summary>
        public static string str_4d62081a_f438_4fa9_813c_cfee1c73b025_Caption {
            get {
                return ResourceManager.GetString("str_4d62081a_f438_4fa9_813c_cfee1c73b025_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Carrier History.
        /// </summary>
        public static string str_4ec6c192_d8fa_4df8_b417_24b23875c64b_Caption {
            get {
                return ResourceManager.GetString("str_4ec6c192_d8fa_4df8_b417_24b23875c64b_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string str_513d7934_f1c4_4cf1_9207_8367c791a045_Caption {
            get {
                return ResourceManager.GetString("str_513d7934_f1c4_4cf1_9207_8367c791a045_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Order Status.
        /// </summary>
        public static string str_54b8159c_3604_423d_8f47_8c62c8be1ee9_Caption {
            get {
                return ResourceManager.GetString("str_54b8159c_3604_423d_8f47_8c62c8be1ee9_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string str_57ec71f5_5a45_4dbe_a066_70cc861a424d_Caption {
            get {
                return ResourceManager.GetString("str_57ec71f5_5a45_4dbe_a066_70cc861a424d_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User Settings.
        /// </summary>
        public static string str_59168e8d_9b97_4a1a_94ba_401cc9f8d807_Caption {
            get {
                return ResourceManager.GetString("str_59168e8d_9b97_4a1a_94ba_401cc9f8d807_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Utilization.
        /// </summary>
        public static string str_591a2cef_6dc1_498f_810c_f32639a36fbe_Caption {
            get {
                return ResourceManager.GetString("str_591a2cef_6dc1_498f_810c_f32639a36fbe_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Order History.
        /// </summary>
        public static string str_59a8f0b2_759d_49a7_9849_99e92d3c6a76_Caption {
            get {
                return ResourceManager.GetString("str_59a8f0b2_759d_49a7_9849_99e92d3c6a76_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Order History.
        /// </summary>
        public static string str_5b23c256_7488_476f_adce_1d5a2788e663_Caption {
            get {
                return ResourceManager.GetString("str_5b23c256_7488_476f_adce_1d5a2788e663_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Load Change Code.
        /// </summary>
        public static string str_6370ae5e_c8b2_428f_9692_09f6a98fcf6c_Caption {
            get {
                return ResourceManager.GetString("str_6370ae5e_c8b2_428f_9692_09f6a98fcf6c_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Code Conversion.
        /// </summary>
        public static string str_64181436_60c9_4521_ae8e_414f231dcc70_Caption {
            get {
                return ResourceManager.GetString("str_64181436_60c9_4521_ae8e_414f231dcc70_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slotting Output.
        /// </summary>
        public static string str_65405fc8_1f66_48fb_8c44_6bf6e0cddc20_Caption {
            get {
                return ResourceManager.GetString("str_65405fc8_1f66_48fb_8c44_6bf6e0cddc20_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Carrier Type.
        /// </summary>
        public static string str_6562b0e9_2118_4889_8fba_355f3fdf4b76_Caption {
            get {
                return ResourceManager.GetString("str_6562b0e9_2118_4889_8fba_355f3fdf4b76_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Layout.
        /// </summary>
        public static string str_66b80c3f_d29e_49e4_9921_81de030bf282_Caption {
            get {
                return ResourceManager.GetString("str_66b80c3f_d29e_49e4_9921_81de030bf282_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Code.
        /// </summary>
        public static string str_67267945_12eb_42ee_a5b6_2b592d7ca0e9_Caption {
            get {
                return ResourceManager.GetString("str_67267945_12eb_42ee_a5b6_2b592d7ca0e9_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Station.
        /// </summary>
        public static string str_6834a494_478f_495a_ae2d_ee0a15a45d6f_Caption {
            get {
                return ResourceManager.GetString("str_6834a494_478f_495a_ae2d_ee0a15a45d6f_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Rule.
        /// </summary>
        public static string str_69b85723_1c26_4154_bea0_bc7754dd3bf4_Caption {
            get {
                return ResourceManager.GetString("str_69b85723_1c26_4154_bea0_bc7754dd3bf4_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Type.
        /// </summary>
        public static string str_6acd82ad_fefe_4578_ad8e_119bf6e2e9fd_Caption {
            get {
                return ResourceManager.GetString("str_6acd82ad_fefe_4578_ad8e_119bf6e2e9fd_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Order.
        /// </summary>
        public static string str_6b73c727_06c4_4854_8bc0_d2e43df4751a_Caption {
            get {
                return ResourceManager.GetString("str_6b73c727_06c4_4854_8bc0_d2e43df4751a_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aisle.
        /// </summary>
        public static string str_6baacce9_c821_45e3_99a8_3db04526cb3a_Caption {
            get {
                return ResourceManager.GetString("str_6baacce9_c821_45e3_99a8_3db04526cb3a_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Units.
        /// </summary>
        public static string str_6c4ea97a_a5da_44a5_b4a7_8af7255514a5_Caption {
            get {
                return ResourceManager.GetString("str_6c4ea97a_a5da_44a5_b4a7_8af7255514a5_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string str_7009472f_06a0_4cef_a51b_83884fd3a0c7_Caption {
            get {
                return ResourceManager.GetString("str_7009472f_06a0_4cef_a51b_83884fd3a0c7_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception Load Carrier.
        /// </summary>
        public static string str_70cd31be_c32f_4847_bff9_42881f1927c2_Caption {
            get {
                return ResourceManager.GetString("str_70cd31be_c32f_4847_bff9_42881f1927c2_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Station.
        /// </summary>
        public static string str_723344ac_1bbd_49ce_99b5_2eb18d376210_Caption {
            get {
                return ResourceManager.GetString("str_723344ac_1bbd_49ce_99b5_2eb18d376210_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string str_75269207_ff6f_4e41_a59b_95c26e495ad1_Caption {
            get {
                return ResourceManager.GetString("str_75269207_ff6f_4e41_a59b_95c26e495ad1_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarder.
        /// </summary>
        public static string str_75427ee4_2d48_4b29_b280_f9d2fa02682c_Caption {
            get {
                return ResourceManager.GetString("str_75427ee4_2d48_4b29_b280_f9d2fa02682c_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Number.
        /// </summary>
        public static string str_7720488f_8dcc_4513_bd48_57c807b7e8a8_Caption {
            get {
                return ResourceManager.GetString("str_7720488f_8dcc_4513_bd48_57c807b7e8a8_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment History.
        /// </summary>
        public static string str_7723ec33_c847_4a25_9e25_6a2442b62dc3_Caption {
            get {
                return ResourceManager.GetString("str_7723ec33_c847_4a25_9e25_6a2442b62dc3_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string str_7b22b960_1f4c_4ff3_9f38_e0178af75d86_Caption {
            get {
                return ResourceManager.GetString("str_7b22b960_1f4c_4ff3_9f38_e0178af75d86_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method of Shipment.
        /// </summary>
        public static string str_7b897761_ee5c_4c6f_b135_d5dfbe9111e8_Caption {
            get {
                return ResourceManager.GetString("str_7b897761_ee5c_4c6f_b135_d5dfbe9111e8_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Station.
        /// </summary>
        public static string str_800609a9_3d74_493c_ad33_7dcffe2fd938_Caption {
            get {
                return ResourceManager.GetString("str_800609a9_3d74_493c_ad33_7dcffe2fd938_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Type.
        /// </summary>
        public static string str_8036ec45_d362_46a4_8ec7_df69d34de23c_Caption {
            get {
                return ResourceManager.GetString("str_8036ec45_d362_46a4_8ec7_df69d34de23c_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Profile.
        /// </summary>
        public static string str_840f06b7_ca74_4a9d_bd6e_2ff24bcbdad1_Caption {
            get {
                return ResourceManager.GetString("str_840f06b7_ca74_4a9d_bd6e_2ff24bcbdad1_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Overview Not Notified.
        /// </summary>
        public static string str_87042984_b50a_4317_8468_aa794a232098_Caption {
            get {
                return ResourceManager.GetString("str_87042984_b50a_4317_8468_aa794a232098_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Type.
        /// </summary>
        public static string str_87d5b1a2_8569_4e2a_9a24_14e2c55d3993_Caption {
            get {
                return ResourceManager.GetString("str_87d5b1a2_8569_4e2a_9a24_14e2c55d3993_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Code.
        /// </summary>
        public static string str_891adebd_06bf_4764_8989_d9ddf7a72d0f_Caption {
            get {
                return ResourceManager.GetString("str_891adebd_06bf_4764_8989_d9ddf7a72d0f_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Audit Template.
        /// </summary>
        public static string str_8dc9d7f4_c1a8_4dfd_9507_de48af07ab27_Caption {
            get {
                return ResourceManager.GetString("str_8dc9d7f4_c1a8_4dfd_9507_de48af07ab27_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string str_9102548e_62ba_4394_a177_d904f67f7419_Caption {
            get {
                return ResourceManager.GetString("str_9102548e_62ba_4394_a177_d904f67f7419_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Load.
        /// </summary>
        public static string str_92f47497_31a3_40fd_b286_974614e18669_Caption {
            get {
                return ResourceManager.GetString("str_92f47497_31a3_40fd_b286_974614e18669_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt History.
        /// </summary>
        public static string str_942b3b63_b929_46d3_9d8d_61e9e99f44be_Caption {
            get {
                return ResourceManager.GetString("str_942b3b63_b929_46d3_9d8d_61e9e99f44be_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Pick Location.
        /// </summary>
        public static string str_954c276a_8029_41f2_857b_efc206d6bd3b_Caption {
            get {
                return ResourceManager.GetString("str_954c276a_8029_41f2_857b_efc206d6bd3b_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound.
        /// </summary>
        public static string str_9615d884_259d_4ba9_bec0_7e25cc230f10_Caption {
            get {
                return ResourceManager.GetString("str_9615d884_259d_4ba9_bec0_7e25cc230f10_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Overview History.
        /// </summary>
        public static string str_96c46a2e_b94f_4628_a486_50617e87ce3f_Caption {
            get {
                return ResourceManager.GetString("str_96c46a2e_b94f_4628_a486_50617e87ce3f_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Load Carrier.
        /// </summary>
        public static string str_9715bdd5_2863_4556_a22b_84f6a48262e7_Caption {
            get {
                return ResourceManager.GetString("str_9715bdd5_2863_4556_a22b_84f6a48262e7_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Item Load.
        /// </summary>
        public static string str_9a063f8a_c150_4a31_94ef_738dd4fa6bc3_Caption {
            get {
                return ResourceManager.GetString("str_9a063f8a_c150_4a31_94ef_738dd4fa6bc3_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Load Type.
        /// </summary>
        public static string str_9d5395b7_2ac2_413b_8fdd_e9b06445ba24_Caption {
            get {
                return ResourceManager.GetString("str_9d5395b7_2ac2_413b_8fdd_e9b06445ba24_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Logon History.
        /// </summary>
        public static string str_9e036564_8ebf_4cd1_8f3c_7b607659eb02_Caption {
            get {
                return ResourceManager.GetString("str_9e036564_8ebf_4cd1_8f3c_7b607659eb02_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data.
        /// </summary>
        public static string str_9e710e29_ceb1_4aee_b375_512987d69d52_Caption {
            get {
                return ResourceManager.GetString("str_9e710e29_ceb1_4aee_b375_512987d69d52_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal History.
        /// </summary>
        public static string str_a0970157_e616_4c62_a7ef_68014df5d82e_Caption {
            get {
                return ResourceManager.GetString("str_a0970157_e616_4c62_a7ef_68014df5d82e_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Order Line History.
        /// </summary>
        public static string str_a0f8467b_2a31_4674_90d8_74c6ca781ab0_Caption {
            get {
                return ResourceManager.GetString("str_a0f8467b_2a31_4674_90d8_74c6ca781ab0_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Carrier.
        /// </summary>
        public static string str_a425c1bc_0b3a_4ab1_89b6_c6897211666e_Caption {
            get {
                return ResourceManager.GetString("str_a425c1bc_0b3a_4ab1_89b6_c6897211666e_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Alias.
        /// </summary>
        public static string str_a482bd8b_d655_4db7_9416_0efd37be665c_Caption {
            get {
                return ResourceManager.GetString("str_a482bd8b_d655_4db7_9416_0efd37be665c_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Task.
        /// </summary>
        public static string str_a49ccb9e_b8a2_45a6_94f2_af72db403b4f_Caption {
            get {
                return ResourceManager.GetString("str_a49ccb9e_b8a2_45a6_94f2_af72db403b4f_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Storage.
        /// </summary>
        public static string str_ab493fd4_01e9_4621_a359_e75b3df18036_Caption {
            get {
                return ResourceManager.GetString("str_ab493fd4_01e9_4621_a359_e75b3df18036_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string str_accb7ed8_c778_421c_915e_a0b2ee1ee212_Caption {
            get {
                return ResourceManager.GetString("str_accb7ed8_c778_421c_915e_a0b2ee1ee212_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Order Line History.
        /// </summary>
        public static string str_ad7f5dd4_2b40_40cd_9843_5f5a62d0ed60_Caption {
            get {
                return ResourceManager.GetString("str_ad7f5dd4_2b40_40cd_9843_5f5a62d0ed60_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Order.
        /// </summary>
        public static string str_b4542a06_0600_4a1e_805f_c05540ed2002_Caption {
            get {
                return ResourceManager.GetString("str_b4542a06_0600_4a1e_805f_c05540ed2002_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Route.
        /// </summary>
        public static string str_b99c5d0e_4dfc_49f8_8aa2_48b6dfbf5d33_Caption {
            get {
                return ResourceManager.GetString("str_b99c5d0e_4dfc_49f8_8aa2_48b6dfbf5d33_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound.
        /// </summary>
        public static string str_bbdba6ff_363f_44ec_be73_0823c7f053c6_Caption {
            get {
                return ResourceManager.GetString("str_bbdba6ff_363f_44ec_be73_0823c7f053c6_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Order Line History.
        /// </summary>
        public static string str_c16fa7b9_0f77_4a71_8c0b_2082b2027e30_Caption {
            get {
                return ResourceManager.GetString("str_c16fa7b9_0f77_4a71_8c0b_2082b2027e30_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Return Order Line History.
        /// </summary>
        public static string str_c17d4dff_a0c7_4716_aace_0d0ce1eaf408_Caption {
            get {
                return ResourceManager.GetString("str_c17d4dff_a0c7_4716_aace_0d0ce1eaf408_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string str_c1d38cb7_71d2_4403_8cea_78985b7bb6e1_Caption {
            get {
                return ResourceManager.GetString("str_c1d38cb7_71d2_4403_8cea_78985b7bb6e1_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Load Carrier to Recall.
        /// </summary>
        public static string str_c6173df1_577b_4d0f_95d8_4e4fbac3c30f_Caption {
            get {
                return ResourceManager.GetString("str_c6173df1_577b_4d0f_95d8_4e4fbac3c30f_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string str_c8ca2805_0187_4213_ad9b_034bae8f1d40_Caption {
            get {
                return ResourceManager.GetString("str_c8ca2805_0187_4213_ad9b_034bae8f1d40_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift Truck.
        /// </summary>
        public static string str_ca434f2f_197e_4d42_9c3b_b53f9e9fd7c5_Caption {
            get {
                return ResourceManager.GetString("str_ca434f2f_197e_4d42_9c3b_b53f9e9fd7c5_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string str_cc7a035a_1e77_4d8f_8e10_e733d3d9fc88_Caption {
            get {
                return ResourceManager.GetString("str_cc7a035a_1e77_4d8f_8e10_e733d3d9fc88_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string str_cd3a112c_cb1f_4ca0_bea7_23c80683e656_Caption {
            get {
                return ResourceManager.GetString("str_cd3a112c_cb1f_4ca0_bea7_23c80683e656_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Zone.
        /// </summary>
        public static string str_d0cac54c_4281_48d6_99df_e5c40d201aa4_Caption {
            get {
                return ResourceManager.GetString("str_d0cac54c_4281_48d6_99df_e5c40d201aa4_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Task History.
        /// </summary>
        public static string str_d1d1b374_c1a5_4aeb_b089_1a66fbfd7bd5_Caption {
            get {
                return ResourceManager.GetString("str_d1d1b374_c1a5_4aeb_b089_1a66fbfd7bd5_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Bar Code.
        /// </summary>
        public static string str_d552f5f0_5c21_4429_ad33_4d83c18a33b8_Caption {
            get {
                return ResourceManager.GetString("str_d552f5f0_5c21_4429_ad33_4d83c18a33b8_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift Truck Type.
        /// </summary>
        public static string str_d69ccb08_b947_46ac_ad5e_901573ca0139_Caption {
            get {
                return ResourceManager.GetString("str_d69ccb08_b947_46ac_ad5e_901573ca0139_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure History.
        /// </summary>
        public static string str_d6a0fb0c_b542_4c82_b4c4_0cb7ffd9da78_Caption {
            get {
                return ResourceManager.GetString("str_d6a0fb0c_b542_4c82_b4c4_0cb7ffd9da78_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Log.
        /// </summary>
        public static string str_d868b23d_96c0_45ba_9ee5_1c7e320059ea_Caption {
            get {
                return ResourceManager.GetString("str_d868b23d_96c0_45ba_9ee5_1c7e320059ea_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment Number.
        /// </summary>
        public static string str_d992244f_b511_4f35_88b4_0fccb710ae8b_Caption {
            get {
                return ResourceManager.GetString("str_d992244f_b511_4f35_88b4_0fccb710ae8b_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy Code.
        /// </summary>
        public static string str_d9d09479_fbb2_4f32_af7f_e1fde028b288_Caption {
            get {
                return ResourceManager.GetString("str_d9d09479_fbb2_4f32_af7f_e1fde028b288_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string str_dc53cabf_59b1_46bf_98c9_f2a7ccdf79f4_Caption {
            get {
                return ResourceManager.GetString("str_dc53cabf_59b1_46bf_98c9_f2a7ccdf79f4_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Return Order.
        /// </summary>
        public static string str_de16eed4_566d_49d1_985f_d9667dc5b88b_Caption {
            get {
                return ResourceManager.GetString("str_de16eed4_566d_49d1_985f_d9667dc5b88b_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Code Filter.
        /// </summary>
        public static string str_df493718_b69d_4578_a917_4779a966ad3b_Caption {
            get {
                return ResourceManager.GetString("str_df493718_b69d_4578_a917_4779a966ad3b_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code Application Identifier.
        /// </summary>
        public static string str_e2884381_70e1_4ea3_a464_12465fd93b03_Caption {
            get {
                return ResourceManager.GetString("str_e2884381_70e1_4ea3_a464_12465fd93b03_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Replenishment Order History.
        /// </summary>
        public static string str_e3cc9314_7244_4f1b_abd0_6c9473455ecf_Caption {
            get {
                return ResourceManager.GetString("str_e3cc9314_7244_4f1b_abd0_6c9473455ecf_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string str_e5399792_a2ab_45ef_9050_e00754fbcf77_Caption {
            get {
                return ResourceManager.GetString("str_e5399792_a2ab_45ef_9050_e00754fbcf77_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string str_e5a185fd_400a_4d32_807e_c2542516691a_Caption {
            get {
                return ResourceManager.GetString("str_e5a185fd_400a_4d32_807e_c2542516691a_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound Overview.
        /// </summary>
        public static string str_e5de424d_4594_4211_9374_4bc2043c57bb_Caption {
            get {
                return ResourceManager.GetString("str_e5de424d_4594_4211_9374_4bc2043c57bb_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Unit Zone.
        /// </summary>
        public static string str_e610ea52_fb47_4a1c_8aef_0753165de965_Caption {
            get {
                return ResourceManager.GetString("str_e610ea52_fb47_4a1c_8aef_0753165de965_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set of Conversion Units.
        /// </summary>
        public static string str_e7020692_0f85_4989_a83b_a7e82e82c775_Caption {
            get {
                return ResourceManager.GetString("str_e7020692_0f85_4989_a83b_a7e82e82c775_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Zone Group.
        /// </summary>
        public static string str_ec5342df_847b_4d0f_8b6c_89aa229d2ada_Caption {
            get {
                return ResourceManager.GetString("str_ec5342df_847b_4d0f_8b6c_89aa229d2ada_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Group.
        /// </summary>
        public static string str_f1b88b5a_668b_449d_98c1_094db5056e1d_Caption {
            get {
                return ResourceManager.GetString("str_f1b88b5a_668b_449d_98c1_094db5056e1d_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string str_f35f5e5f_7605_4824_ac1e_8b4790cc3f7a_Caption {
            get {
                return ResourceManager.GetString("str_f35f5e5f_7605_4824_ac1e_8b4790cc3f7a_Caption", resourceCulture);
            }
        }
    }
}
