//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
// 
#pragma warning disable 1591

namespace WebServiceTester.OrderPortalService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderPortalServiceSoap", Namespace="http://im.se/wms/webservices/")]
    public partial class OrderPortalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WhoAmIOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerOrderHeadInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerOrderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerOrderLineRangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OrderPortalService() {
            this.Url = global::WebServiceTester.Properties.Settings.Default.WebServiceTester_OrderPortalService_OrderPortalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WhoAmICompletedEventHandler WhoAmICompleted;
        
        /// <remarks/>
        public event GetCustomerOrderHeadInfoCompletedEventHandler GetCustomerOrderHeadInfoCompleted;
        
        /// <remarks/>
        public event GetCustomerOrderInfoCompletedEventHandler GetCustomerOrderInfoCompleted;
        
        /// <remarks/>
        public event GetCustomerOrderLineRangeCompletedEventHandler GetCustomerOrderLineRangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://im.se/wms/webservices/WhoAmI", RequestNamespace="http://im.se/wms/webservices/", ResponseNamespace="http://im.se/wms/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WhoAmI() {
            object[] results = this.Invoke("WhoAmI", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WhoAmIAsync() {
            this.WhoAmIAsync(null);
        }
        
        /// <remarks/>
        public void WhoAmIAsync(object userState) {
            if ((this.WhoAmIOperationCompleted == null)) {
                this.WhoAmIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhoAmIOperationCompleted);
            }
            this.InvokeAsync("WhoAmI", new object[0], this.WhoAmIOperationCompleted, userState);
        }
        
        private void OnWhoAmIOperationCompleted(object arg) {
            if ((this.WhoAmICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WhoAmICompleted(this, new WhoAmICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://im.se/wms/webservices/GetCustomerOrderHeadInfo", RequestNamespace="http://im.se/wms/webservices/", ResponseNamespace="http://im.se/wms/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerOrderHeadInfoDoc GetCustomerOrderHeadInfo(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> OrderSequence) {
            object[] results = this.Invoke("GetCustomerOrderHeadInfo", new object[] {
                        PartnerName,
                        LanguageId,
                        ClientIdentity,
                        OrderNumber,
                        OrderSequence});
            return ((CustomerOrderHeadInfoDoc)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerOrderHeadInfoAsync(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, System.Nullable<int> OrderSequence) {
            this.GetCustomerOrderHeadInfoAsync(PartnerName, LanguageId, ClientIdentity, OrderNumber, OrderSequence, null);
        }
        
        /// <remarks/>
        public void GetCustomerOrderHeadInfoAsync(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, System.Nullable<int> OrderSequence, object userState) {
            if ((this.GetCustomerOrderHeadInfoOperationCompleted == null)) {
                this.GetCustomerOrderHeadInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerOrderHeadInfoOperationCompleted);
            }
            this.InvokeAsync("GetCustomerOrderHeadInfo", new object[] {
                        PartnerName,
                        LanguageId,
                        ClientIdentity,
                        OrderNumber,
                        OrderSequence}, this.GetCustomerOrderHeadInfoOperationCompleted, userState);
        }
        
        private void OnGetCustomerOrderHeadInfoOperationCompleted(object arg) {
            if ((this.GetCustomerOrderHeadInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerOrderHeadInfoCompleted(this, new GetCustomerOrderHeadInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://im.se/wms/webservices/GetCustomerOrderInfo", RequestNamespace="http://im.se/wms/webservices/", ResponseNamespace="http://im.se/wms/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerOrderInfoDoc GetCustomerOrderInfo(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> OrderSequence) {
            object[] results = this.Invoke("GetCustomerOrderInfo", new object[] {
                        PartnerName,
                        LanguageId,
                        ClientIdentity,
                        OrderNumber,
                        OrderSequence});
            return ((CustomerOrderInfoDoc)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerOrderInfoAsync(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, System.Nullable<int> OrderSequence) {
            this.GetCustomerOrderInfoAsync(PartnerName, LanguageId, ClientIdentity, OrderNumber, OrderSequence, null);
        }
        
        /// <remarks/>
        public void GetCustomerOrderInfoAsync(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, System.Nullable<int> OrderSequence, object userState) {
            if ((this.GetCustomerOrderInfoOperationCompleted == null)) {
                this.GetCustomerOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerOrderInfoOperationCompleted);
            }
            this.InvokeAsync("GetCustomerOrderInfo", new object[] {
                        PartnerName,
                        LanguageId,
                        ClientIdentity,
                        OrderNumber,
                        OrderSequence}, this.GetCustomerOrderInfoOperationCompleted, userState);
        }
        
        private void OnGetCustomerOrderInfoOperationCompleted(object arg) {
            if ((this.GetCustomerOrderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerOrderInfoCompleted(this, new GetCustomerOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://im.se/wms/webservices/GetCustomerOrderLineRange", RequestNamespace="http://im.se/wms/webservices/", ResponseNamespace="http://im.se/wms/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerOrderLineRangeDoc GetCustomerOrderLineRange(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> OrderSequence, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> FirstLinePosition, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> LastLinePosition) {
            object[] results = this.Invoke("GetCustomerOrderLineRange", new object[] {
                        PartnerName,
                        LanguageId,
                        ClientIdentity,
                        OrderNumber,
                        OrderSequence,
                        FirstLinePosition,
                        LastLinePosition});
            return ((CustomerOrderLineRangeDoc)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerOrderLineRangeAsync(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, System.Nullable<int> OrderSequence, System.Nullable<int> FirstLinePosition, System.Nullable<int> LastLinePosition) {
            this.GetCustomerOrderLineRangeAsync(PartnerName, LanguageId, ClientIdentity, OrderNumber, OrderSequence, FirstLinePosition, LastLinePosition, null);
        }
        
        /// <remarks/>
        public void GetCustomerOrderLineRangeAsync(string PartnerName, string LanguageId, string ClientIdentity, string OrderNumber, System.Nullable<int> OrderSequence, System.Nullable<int> FirstLinePosition, System.Nullable<int> LastLinePosition, object userState) {
            if ((this.GetCustomerOrderLineRangeOperationCompleted == null)) {
                this.GetCustomerOrderLineRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerOrderLineRangeOperationCompleted);
            }
            this.InvokeAsync("GetCustomerOrderLineRange", new object[] {
                        PartnerName,
                        LanguageId,
                        ClientIdentity,
                        OrderNumber,
                        OrderSequence,
                        FirstLinePosition,
                        LastLinePosition}, this.GetCustomerOrderLineRangeOperationCompleted, userState);
        }
        
        private void OnGetCustomerOrderLineRangeOperationCompleted(object arg) {
            if ((this.GetCustomerOrderLineRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerOrderLineRangeCompleted(this, new GetCustomerOrderLineRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/orderportal")]
    public partial class CustomerOrderHeadInfoDoc {
        
        private CustomerOrder[] aCustomerOrderListField;
        
        private CustomerWorkOrder[] aCustomerWorkOrderListField;
        
        private Departure[] aDepartureListField;
        
        private OrderQuantities[] aOrderQuantitiesListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aCustomerOrderList", IsNullable=true)]
        public CustomerOrder[] aCustomerOrderList {
            get {
                return this.aCustomerOrderListField;
            }
            set {
                this.aCustomerOrderListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aCustomerWorkOrderList", IsNullable=true)]
        public CustomerWorkOrder[] aCustomerWorkOrderList {
            get {
                return this.aCustomerWorkOrderListField;
            }
            set {
                this.aCustomerWorkOrderListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aDepartureList", IsNullable=true)]
        public Departure[] aDepartureList {
            get {
                return this.aDepartureListField;
            }
            set {
                this.aDepartureListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aOrderQuantitiesList", IsNullable=true)]
        public OrderQuantities[] aOrderQuantitiesList {
            get {
                return this.aOrderQuantitiesListField;
            }
            set {
                this.aOrderQuantitiesListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/orderportal")]
    public partial class CustomerOrder {
        
        private string clientIdentityField;
        
        private string orderNumberField;
        
        private System.Nullable<int> orderSequenceField;
        
        private string orderStatusCodeField;
        
        private string orderStatusTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientIdentity {
            get {
                return this.clientIdentityField;
            }
            set {
                this.clientIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OrderSequence {
            get {
                return this.orderSequenceField;
            }
            set {
                this.orderSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderStatusCode {
            get {
                return this.orderStatusCodeField;
            }
            set {
                this.orderStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderStatusText {
            get {
                return this.orderStatusTextField;
            }
            set {
                this.orderStatusTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/orderportal")]
    public partial class CustomerOrderLineRangeDoc {
        
        private CustomerOrder[] aCustomerOrderListField;
        
        private CustomerWorkOrder[] aCustomerWorkOrderListField;
        
        private Departure[] aDepartureListField;
        
        private OrderQuantities[] aOrderQuantitiesListField;
        
        private CustomerOrderRow[] aCustomerOrderRowListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aCustomerOrderList", IsNullable=true)]
        public CustomerOrder[] aCustomerOrderList {
            get {
                return this.aCustomerOrderListField;
            }
            set {
                this.aCustomerOrderListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aCustomerWorkOrderList", IsNullable=true)]
        public CustomerWorkOrder[] aCustomerWorkOrderList {
            get {
                return this.aCustomerWorkOrderListField;
            }
            set {
                this.aCustomerWorkOrderListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aDepartureList", IsNullable=true)]
        public Departure[] aDepartureList {
            get {
                return this.aDepartureListField;
            }
            set {
                this.aDepartureListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aOrderQuantitiesList", IsNullable=true)]
        public OrderQuantities[] aOrderQuantitiesList {
            get {
                return this.aOrderQuantitiesListField;
            }
            set {
                this.aOrderQuantitiesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aCustomerOrderRowList", IsNullable=true)]
        public CustomerOrderRow[] aCustomerOrderRowList {
            get {
                return this.aCustomerOrderRowListField;
            }
            set {
                this.aCustomerOrderRowListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/orderportal")]
    public partial class CustomerWorkOrder {
        
        private string clientIdentityField;
        
        private string orderNumberField;
        
        private System.Nullable<int> orderSequenceField;
        
        private System.Nullable<int> subSequenceField;
        
        private string orderStatusCodeField;
        
        private string orderStatusTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientIdentity {
            get {
                return this.clientIdentityField;
            }
            set {
                this.clientIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OrderSequence {
            get {
                return this.orderSequenceField;
            }
            set {
                this.orderSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SubSequence {
            get {
                return this.subSequenceField;
            }
            set {
                this.subSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderStatusCode {
            get {
                return this.orderStatusCodeField;
            }
            set {
                this.orderStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderStatusText {
            get {
                return this.orderStatusTextField;
            }
            set {
                this.orderStatusTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/orderportal")]
    public partial class Departure {
        
        private string clientIdentityField;
        
        private string orderNumberField;
        
        private System.Nullable<int> orderSequenceField;
        
        private System.Nullable<int> subSequenceField;
        
        private string departureIdentityField;
        
        private string pickStatusCodeField;
        
        private string pickStatusTextField;
        
        private string loadStatusCodeField;
        
        private string loadStatusTextField;
        
        private System.Nullable<System.DateTime> departureTimeField;
        
        private string methodOfShipmentIdField;
        
        private string methodOfShipmentNameField;
        
        private string forwarderIdField;
        
        private string forwarderNameField;
        
        private string dispatchRouteField;
        
        private string vehicleIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientIdentity {
            get {
                return this.clientIdentityField;
            }
            set {
                this.clientIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OrderSequence {
            get {
                return this.orderSequenceField;
            }
            set {
                this.orderSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SubSequence {
            get {
                return this.subSequenceField;
            }
            set {
                this.subSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DepartureIdentity {
            get {
                return this.departureIdentityField;
            }
            set {
                this.departureIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickStatusCode {
            get {
                return this.pickStatusCodeField;
            }
            set {
                this.pickStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickStatusText {
            get {
                return this.pickStatusTextField;
            }
            set {
                this.pickStatusTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoadStatusCode {
            get {
                return this.loadStatusCodeField;
            }
            set {
                this.loadStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoadStatusText {
            get {
                return this.loadStatusTextField;
            }
            set {
                this.loadStatusTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DepartureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MethodOfShipmentId {
            get {
                return this.methodOfShipmentIdField;
            }
            set {
                this.methodOfShipmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MethodOfShipmentName {
            get {
                return this.methodOfShipmentNameField;
            }
            set {
                this.methodOfShipmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ForwarderId {
            get {
                return this.forwarderIdField;
            }
            set {
                this.forwarderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ForwarderName {
            get {
                return this.forwarderNameField;
            }
            set {
                this.forwarderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DispatchRoute {
            get {
                return this.dispatchRouteField;
            }
            set {
                this.dispatchRouteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VehicleId {
            get {
                return this.vehicleIdField;
            }
            set {
                this.vehicleIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/orderportal")]
    public partial class OrderQuantities {
        
        private string clientIdentityField;
        
        private string orderNumberField;
        
        private System.Nullable<int> orderSequenceField;
        
        private System.Nullable<int> subSequenceField;
        
        private System.Nullable<double> totalNoOfLinesField;
        
        private System.Nullable<double> pickedNoOfLinesField;
        
        private System.Nullable<double> estimatedWeightField;
        
        private System.Nullable<double> estimatedVolumeField;
        
        private System.Nullable<double> plannedNoOfPalletsField;
        
        private System.Nullable<double> plannedNoOfLowestUMField;
        
        private System.Nullable<double> plannedVolumeField;
        
        private System.Nullable<double> plannedWeightField;
        
        private System.Nullable<double> pickedNoOfPalletsField;
        
        private System.Nullable<double> pickedNoOfLowestUMField;
        
        private System.Nullable<double> pickedVolumeField;
        
        private System.Nullable<double> pickedWeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientIdentity {
            get {
                return this.clientIdentityField;
            }
            set {
                this.clientIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OrderSequence {
            get {
                return this.orderSequenceField;
            }
            set {
                this.orderSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SubSequence {
            get {
                return this.subSequenceField;
            }
            set {
                this.subSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> TotalNoOfLines {
            get {
                return this.totalNoOfLinesField;
            }
            set {
                this.totalNoOfLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PickedNoOfLines {
            get {
                return this.pickedNoOfLinesField;
            }
            set {
                this.pickedNoOfLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> EstimatedWeight {
            get {
                return this.estimatedWeightField;
            }
            set {
                this.estimatedWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> EstimatedVolume {
            get {
                return this.estimatedVolumeField;
            }
            set {
                this.estimatedVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PlannedNoOfPallets {
            get {
                return this.plannedNoOfPalletsField;
            }
            set {
                this.plannedNoOfPalletsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PlannedNoOfLowestUM {
            get {
                return this.plannedNoOfLowestUMField;
            }
            set {
                this.plannedNoOfLowestUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PlannedVolume {
            get {
                return this.plannedVolumeField;
            }
            set {
                this.plannedVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PlannedWeight {
            get {
                return this.plannedWeightField;
            }
            set {
                this.plannedWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PickedNoOfPallets {
            get {
                return this.pickedNoOfPalletsField;
            }
            set {
                this.pickedNoOfPalletsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PickedNoOfLowestUM {
            get {
                return this.pickedNoOfLowestUMField;
            }
            set {
                this.pickedNoOfLowestUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PickedVolume {
            get {
                return this.pickedVolumeField;
            }
            set {
                this.pickedVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PickedWeight {
            get {
                return this.pickedWeightField;
            }
            set {
                this.pickedWeightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/orderportal")]
    public partial class CustomerOrderRow {
        
        private string clientIdentityField;
        
        private string orderNumberField;
        
        private System.Nullable<int> orderSequenceField;
        
        private System.Nullable<int> subSequenceField;
        
        private System.Nullable<int> linePositionField;
        
        private System.Nullable<int> lineSequenceField;
        
        private System.Nullable<int> lineKitPositionField;
        
        private string lineStatusField;
        
        private System.Nullable<double> orderedQuantityField;
        
        private System.Nullable<double> pickedQuantityField;
        
        private System.Nullable<double> discrepancyQuantityField;
        
        private string discrepancyCodeField;
        
        private string discrepancyTextField;
        
        private string externalDiscrepancyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientIdentity {
            get {
                return this.clientIdentityField;
            }
            set {
                this.clientIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OrderSequence {
            get {
                return this.orderSequenceField;
            }
            set {
                this.orderSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SubSequence {
            get {
                return this.subSequenceField;
            }
            set {
                this.subSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LinePosition {
            get {
                return this.linePositionField;
            }
            set {
                this.linePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LineSequence {
            get {
                return this.lineSequenceField;
            }
            set {
                this.lineSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LineKitPosition {
            get {
                return this.lineKitPositionField;
            }
            set {
                this.lineKitPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LineStatus {
            get {
                return this.lineStatusField;
            }
            set {
                this.lineStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> OrderedQuantity {
            get {
                return this.orderedQuantityField;
            }
            set {
                this.orderedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PickedQuantity {
            get {
                return this.pickedQuantityField;
            }
            set {
                this.pickedQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> DiscrepancyQuantity {
            get {
                return this.discrepancyQuantityField;
            }
            set {
                this.discrepancyQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DiscrepancyCode {
            get {
                return this.discrepancyCodeField;
            }
            set {
                this.discrepancyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DiscrepancyText {
            get {
                return this.discrepancyTextField;
            }
            set {
                this.discrepancyTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExternalDiscrepancyCode {
            get {
                return this.externalDiscrepancyCodeField;
            }
            set {
                this.externalDiscrepancyCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/orderportal")]
    public partial class CustomerOrderInfoDoc {
        
        private CustomerOrder[] aCustomerOrderListField;
        
        private CustomerWorkOrder[] aCustomerWorkOrderListField;
        
        private Departure[] aDepartureListField;
        
        private OrderQuantities[] aOrderQuantitiesListField;
        
        private CustomerOrderRow[] aCustomerOrderRowListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aCustomerOrderList", IsNullable=true)]
        public CustomerOrder[] aCustomerOrderList {
            get {
                return this.aCustomerOrderListField;
            }
            set {
                this.aCustomerOrderListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aCustomerWorkOrderList", IsNullable=true)]
        public CustomerWorkOrder[] aCustomerWorkOrderList {
            get {
                return this.aCustomerWorkOrderListField;
            }
            set {
                this.aCustomerWorkOrderListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aDepartureList", IsNullable=true)]
        public Departure[] aDepartureList {
            get {
                return this.aDepartureListField;
            }
            set {
                this.aDepartureListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aOrderQuantitiesList", IsNullable=true)]
        public OrderQuantities[] aOrderQuantitiesList {
            get {
                return this.aOrderQuantitiesListField;
            }
            set {
                this.aOrderQuantitiesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aCustomerOrderRowList", IsNullable=true)]
        public CustomerOrderRow[] aCustomerOrderRowList {
            get {
                return this.aCustomerOrderRowListField;
            }
            set {
                this.aCustomerOrderRowListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void WhoAmICompletedEventHandler(object sender, WhoAmICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WhoAmICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WhoAmICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetCustomerOrderHeadInfoCompletedEventHandler(object sender, GetCustomerOrderHeadInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerOrderHeadInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerOrderHeadInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerOrderHeadInfoDoc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerOrderHeadInfoDoc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetCustomerOrderInfoCompletedEventHandler(object sender, GetCustomerOrderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerOrderInfoDoc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerOrderInfoDoc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetCustomerOrderLineRangeCompletedEventHandler(object sender, GetCustomerOrderLineRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerOrderLineRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerOrderLineRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerOrderLineRangeDoc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerOrderLineRangeDoc)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591