#
# makefile 17/12/2004
# 
# Copyright (c) 2004 - 2005 Industri-Matematik AB. All rights reserved.
#

# --------------------------------------------
# Description Blocks
# --------------------------------------------

INSTALL : 
  installutil /SystemId=WMSDevelop .\bin\debug\IMIServer.exe


CLEAN :
  installutil /u /SystemId=WMSDevelop .\bin\debug\IMIServer.exe

# end makefile
