/*
  File           : 

  Description    : Interface classes for inbound data.
                   This code was generated, do not edit.

*/
using System;
using System.Data;
using System.Xml.Serialization;

namespace Imi.Wms.WebServices.ExternalInterfaceRMS
{
  public class ExternalInterface
  {
    public string _Debug()
    {
      return "Generated on   : 2017-09-08 11:57:02\r\n" +
             "Generated by   : SWG\\aron@SE0133D\r\n" +
             "Generated in   : C:\\projects\\views\\aron_80M_ss\\dotnet\\source\\CodeGenerators\\wscc\r\n";
    }
  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class MethodOfShipmentDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string           OPCODE;                    /* .                 */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           DeliveryMethod;            /* DM.DLVRYMETH_ID   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           DeliveryMethodDescription; /* DM.DLVRYMETH_NAME */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> MinimumAllowedVolume;      /* DM.MINVOL         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> MaximumAllowedVolume;      /* DM.MAXVOL         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> MinimumAllowedWeight;      /* DM.MINWGT         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> MaximumAllowedWeight;      /* DM.MAXWGT         */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class ForwarderDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string OPCODE;                /* .           */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ForwarderIdentity;     /* FRE.FREID   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ForwarderIdentityName; /* FRE.FRENAME */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class VehicleTypeDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string           OPCODE;                 /* .                   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           VehicleTypeIdentity;    /* VEHTYP.VEHTYPID     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           VehicleTypeDescription; /* VEHTYP.VEHTYPNAME   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> TotalWeightCapacity;    /* VEHTYP.MAXWGT       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> TotalVolumeCapacity;    /* VEHTYP.MAXVOL       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> TotalSpaceCapacity;     /* VEHTYP.MAXAREA      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           Instructions;           /* VEHTYP.INSTRUCTIONS */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class VehicleTypePTTDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string           OPCODE;                   /* .                            */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           VehicleTypeIdentity;      /* VEHTYP_ARTTRPTYP.VEHTYPID    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           ProductTransportIdentity; /* VEHTYP_ARTTRPTYP.ARTTRPTYPID */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> MaximumWeight;            /* VEHTYP_ARTTRPTYP.MAXWGT      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> MaximumVolume;            /* VEHTYP_ARTTRPTYP.MAXVOL      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> MaximumSpace;             /* VEHTYP_ARTTRPTYP.MAXAREA     */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class RouteDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string OPCODE;                    /* .                   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RouteIdentity;             /* ROUTE.ROUTE_ID      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RouteDescription;          /* ROUTE.ROUTE_NAME    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FromNodeIdentity;          /* ROUTE.NODE_ID       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string DeliveryMethod;            /* ROUTE.DLVRYMETH_ID  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ForwarderIdentity;         /* ROUTE.FREID         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string VehicleTypeIdentity;       /* ROUTE.VEHTYPID      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string VehicleIdentity;           /* ROUTE.VMUID         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string DriverIdentity;            /* ROUTE.VMUDRIVER     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Instructions;              /* ROUTE.INSTRUCTIONS  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CheckProductTransportType; /* ROUTE.CHK_ARTTRPTYP */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class RouteNodeDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string             OPCODE;                      /* .                              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             RouteIdentity;               /* ROUTE_NODE.ROUTE_ID            */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             FromNodeIdentity;            /* ROUTE_NODE.NODE_ID             */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ToNodeIdentity;              /* ROUTE_NODE.TO_NODE_ID          */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<int>      StopSequence;                /* ROUTE_NODE.STOP_SEQ            */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             StopType;                    /* ROUTE_NODE.STOP_TYPE           */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PrevNodeDrivingTime_Day;     /* .                              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PrevNodeDrivingTime_Hour;    /* .                              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PrevNodeDrivingTime_Minutes; /* .                              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   NodeStopTime_Day;            /* .                              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   NodeStopTime_Hour;           /* .                              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   NodeStopTime_Minutes;        /* .                              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PrevNodeDrivingDistance;     /* ROUTE_NODE.TRPDIST             */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> EarliestArrivalTime;         /* ROUTE_NODE.FPDTM_STOP          */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> LatestArrivalTime;           /* ROUTE_NODE.LPDTM_STOP          */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             Instructions;                /* ROUTE_NODE.INSTRUCTIONS        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ReceiveTransitGoods_Mon;     /* ROUTE_NODE_DELVRY.CW_DELVRY_WK */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ReceiveTransitGoods_Tue;     /* ROUTE_NODE_DELVRY.CW_DELVRY_WK */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ReceiveTransitGoods_Wed;     /* ROUTE_NODE_DELVRY.CW_DELVRY_WK */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ReceiveTransitGoods_Thu;     /* ROUTE_NODE_DELVRY.CW_DELVRY_WK */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ReceiveTransitGoods_Fri;     /* ROUTE_NODE_DELVRY.CW_DELVRY_WK */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ReceiveTransitGoods_Sat;     /* ROUTE_NODE_DELVRY.CW_DELVRY_WK */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ReceiveTransitGoods_Sun;     /* ROUTE_NODE_DELVRY.CW_DELVRY_WK */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class RouteNodeTransitNodeDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string OPCODE;              /* .                                       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string RouteIdentity;       /* ROUTE_NODE_TRANSIT_NODE.ROUTE_ID        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FromNodeIdentity;    /* ROUTE_NODE_TRANSIT_NODE.NODE_ID         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ToNodeIdentity;      /* ROUTE_NODE_TRANSIT_NODE.TO_NODE_ID      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TransitNodeIdentity; /* ROUTE_NODE_TRANSIT_NODE.TRANSIT_NODE_ID */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class DepartureDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string             OPCODE;                     /* .                   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DepartureIdentity;          /* DEP.DEPID           */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DepartureIdentityReference; /* DEP.DEPID_REF       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             FromNodeIdentity;           /* DEP.NODE_ID         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> PlannedDepartureDateTime;   /* DEP.PLAN_DEPDTM     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             RouteIdentity;              /* DEP.ROUTE_ID        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DeliveryMethod;             /* DEP.DLVRYMETH_ID    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ForwarderIdentity;          /* DEP.FREID           */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             VehicleTypeIdentity;        /* DEP.VEHTYPID        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             VehicleIdentity;            /* DEP.VMUID           */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DriverIdentity;             /* DEP.VMUDRIVER       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             Instructions;               /* DEP.INSTRUCTIONS    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             CheckProductTransportType;  /* DEP.CHK_ARTTRPTYP   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PreBookedWeight;            /* DEP.PRE_BOOKED_WGT  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PreBookedVolume;            /* DEP.PRE_BOOKED_VOL  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PreBookedSpace;             /* DEP.PRE_BOOKED_AREA */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class DepartureNodeDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string             OPCODE;                      /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DepartureIdentity;           /* DEPNODE.DEPID        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DepartureIdentityReference;  /* DEP.DEPID_REF        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ToNodeIdentity;              /* DEPNODE.NODE_ID      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<int>      StopSequence;                /* DEPNODE.STOP_SEQ     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             StopType;                    /* DEPNODE.STOP_TYPE    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PrevNodeDrivingTime_Day;     /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PrevNodeDrivingTime_Hour;    /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PrevNodeDrivingTime_Minutes; /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   NodeStopTime_Day;            /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   NodeStopTime_Hour;           /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   NodeStopTime_Minutes;        /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PrevNodeDrivingDistance;     /* DEPNODE.TRPDIST      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> EarliestArrivalTime;         /* DEPNODE.FPTME_STOP   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> LatestArrivalTime;           /* DEPNODE.LPTME_STOP   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             Instructions;                /* DEPNODE.INSTRUCTIONS */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ReceiveTransitGoods;         /* DEPNODE.CW_DELVRY    */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class DepartureNodeTransitNodeDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string OPCODE;                     /* .                                  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string DepartureIdentity;          /* DEPNODETRANSITNODE.DEPID           */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string DepartureIdentityReference; /* DEP.DEPID_REF                      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ToNodeIdentity;             /* DEPNODETRANSITNODE.TO_NODE_ID      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TransitNodeIdentity;        /* DEPNODETRANSITNODE.TRANSIT_NODE_ID */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class PrebookedTransitOrderDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string             OPCODE;                      /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             PreBookedTransitOrderNumber; /* DEPLOAD.COID         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             PreBookedTransitOrderRef;    /* DEPLOAD.CO_REF       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             FromNodeIdentity;            /* DEPLOAD.FROM_NODE_ID */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ToNodeIdentity;              /* DEPLOAD.TO_NODE_ID   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ProductTransportIdentity;    /* DEPLOAD.ARTTRPTYPID  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PlannedWeight;               /* DEPLOAD.PLANWGT      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PlannedVolume;               /* DEPLOAD.PLANVOL      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PlannedSpace;                /* DEPLOAD.PLANAREA     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ZipCode;                     /* DEPLOAD.POSTCODE     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             CountryCode;                 /* DEPLOAD.COUNTRYCODE  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DeliveryMethod;              /* DEPLOAD.DLVRYMETH_ID */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> AcknowledgedShipDtm;         /* .                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             SearchReference;             /* DEPLOAD.SEARCH_REF   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             OriginNodeIdentity;          /* DEPLOAD.ORIGIN_ID    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             OriginNodeName;              /* DEPLOAD.ORIGIN_NAME  */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class CustomerOrderDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string             OPCODE;                   /* .                                     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ClientIdentity;           /* DEPLOAD.COMPANY_ID                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             CustomerOrderNumber;      /* DEPLOAD.COID                          */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   CustomerOrderSequence;    /* MSG_OUT_DEPLOAD.CUSTOMERORDERSEQUENCE */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             FromNodeIdentity;         /* DEPLOAD.FROM_NODE_ID                  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ToNodeIdentity;           /* DEPLOAD.TO_NODE_ID                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ProductTransportIdentity; /* DEPLOAD.ARTTRPTYPID                   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PlannedWeight;            /* DEPLOAD.PLANWGT                       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PlannedVolume;            /* DEPLOAD.PLANVOL                       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double>   PlannedSpace;             /* DEPLOAD.PLANAREA                      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DepartureIdentity;        /* DEPLOAD.DEPID                         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ZipCode;                  /* DEPLOAD.POSTCODE                      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             CountryCode;              /* DEPLOAD.COUNTRYCODE                   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DeliveryMethod;           /* DEPLOAD.DLVRYMETH_ID                  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ViaNodeIdentity;          /* DEPLOAD.TO_NODE_ID                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DateSelectionType;        /* DEPLOAD.DATE_SELECTION_TYPE           */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> FirstPlannedShipDtm;      /* DEPLOAD.FPSHIPDTM                     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> LastPlannedShipDtm;       /* DEPLOAD.LPSHIPDTM                     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> FirstPlannedDeliveryDtm;  /* DEPLOAD.FPDELDTM                      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> LastPlannedDeliveryDtm;   /* DEPLOAD.LPDELDTM                      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             PlanLoad;                 /* .                                     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             CustomerOrderClass;       /* COTYP.COTYPID                         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             SearchReference;          /* DEPLOAD.SEARCH_REF                    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ForceURL;                 /* MSG_IN.URL                            */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             AllowTransit;             /* .                                     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             DepartureLoadIdentity;    /* DEPLOAD.DEPLOAD_ID                    */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class NodePartyDoc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string OPCODE;               /* .                       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyIdentity;        /* NODE_PARTY.PARTY_ID     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyQualifier;       /* NODE_PARTY.PARTY_QUAL   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ClientIdentity;       /* NODE_PARTY.COMPANY_ID   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ClientName;           /* NODE_PARTY.COMPANY_NAME */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string NodeIdentity;         /* NODE_PARTY.NODE_ID      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyName1;           /* NODE_PARTY.NAME1        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyName2;           /* NODE_PARTY.NAME2        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyName3;           /* NODE_PARTY.NAME3        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyName4;           /* NODE_PARTY.NAME4        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyName5;           /* NODE_PARTY.NAME5        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyAddress1;        /* NODE_PARTY.ADDRESS1     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyAddress2;        /* NODE_PARTY.ADDRESS2     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyAddress3;        /* NODE_PARTY.ADDRESS3     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PartyAddress4;        /* NODE_PARTY.ADDRESS4     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ZipCode;              /* NODE_PARTY.POSTCODE     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string City;                 /* NODE_PARTY.CITY         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Region;               /* NODE_PARTY.REGION       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CountryCode;          /* NODE_PARTY.COUNTRYCODE  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Country;              /* NODE_PARTY.COUNTRY      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Division;             /* NODE_PARTY.DIVISION     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Phone;                /* NODE_PARTY.PHONE        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Fax;                  /* NODE_PARTY.FAX          */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Telex;                /* NODE_PARTY.TELEX        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Email;                /* NODE_PARTY.EMAIL        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OrganizationNumber;   /* NODE_PARTY.ORG_NUMBER   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string GlobalLocationNumber; /* NODE_PARTY.GLOBAL_LOC   */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Latitude;             /* NODE_PARTY.LATITUDE     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Longitude;            /* NODE_PARTY.LONGITUDE    */


  }

}
