//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace WebServiceTester.OrderService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OrderServiceBinding", Namespace="http://im.se/webservices/c3pl")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(searchResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseParameters))]
    public partial class OrderWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOpenOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrderDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerOrderTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMethodOfShipmentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OrderWebService() {
            this.Url = global::WebServiceTester.Properties.Settings.Default.WebServiceTester_OrderService_OrderWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getOpenOrdersCompletedEventHandler getOpenOrdersCompleted;
        
        /// <remarks/>
        public event getOrderDetailsCompletedEventHandler getOrderDetailsCompleted;
        
        /// <remarks/>
        public event saveOrderCompletedEventHandler saveOrderCompleted;
        
        /// <remarks/>
        public event validateOrderCompletedEventHandler validateOrderCompleted;
        
        /// <remarks/>
        public event getCustomerOrderTypesCompletedEventHandler getCustomerOrderTypesCompleted;
        
        /// <remarks/>
        public event getMethodOfShipmentsCompletedEventHandler getMethodOfShipmentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://im.se/webservices/c3pl", ResponseNamespace="http://im.se/webservices/c3pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public orderSearchResult getOpenOrders([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] orderSearchParameters orderSearchParameters) {
            object[] results = this.Invoke("getOpenOrders", new object[] {
                        orderSearchParameters});
            return ((orderSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void getOpenOrdersAsync(orderSearchParameters orderSearchParameters) {
            this.getOpenOrdersAsync(orderSearchParameters, null);
        }
        
        /// <remarks/>
        public void getOpenOrdersAsync(orderSearchParameters orderSearchParameters, object userState) {
            if ((this.getOpenOrdersOperationCompleted == null)) {
                this.getOpenOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOpenOrdersOperationCompleted);
            }
            this.InvokeAsync("getOpenOrders", new object[] {
                        orderSearchParameters}, this.getOpenOrdersOperationCompleted, userState);
        }
        
        private void OngetOpenOrdersOperationCompleted(object arg) {
            if ((this.getOpenOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOpenOrdersCompleted(this, new getOpenOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://im.se/webservices/c3pl", ResponseNamespace="http://im.se/webservices/c3pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public order getOrderDetails([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] orderSearchParameters orderSearchParameters) {
            object[] results = this.Invoke("getOrderDetails", new object[] {
                        orderSearchParameters});
            return ((order)(results[0]));
        }
        
        /// <remarks/>
        public void getOrderDetailsAsync(orderSearchParameters orderSearchParameters) {
            this.getOrderDetailsAsync(orderSearchParameters, null);
        }
        
        /// <remarks/>
        public void getOrderDetailsAsync(orderSearchParameters orderSearchParameters, object userState) {
            if ((this.getOrderDetailsOperationCompleted == null)) {
                this.getOrderDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrderDetailsOperationCompleted);
            }
            this.InvokeAsync("getOrderDetails", new object[] {
                        orderSearchParameters}, this.getOrderDetailsOperationCompleted, userState);
        }
        
        private void OngetOrderDetailsOperationCompleted(object arg) {
            if ((this.getOrderDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrderDetailsCompleted(this, new getOrderDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://im.se/webservices/c3pl", ResponseNamespace="http://im.se/webservices/c3pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public order saveOrder([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] orderSaveParameters orderSaveParameters) {
            object[] results = this.Invoke("saveOrder", new object[] {
                        orderSaveParameters});
            return ((order)(results[0]));
        }
        
        /// <remarks/>
        public void saveOrderAsync(orderSaveParameters orderSaveParameters) {
            this.saveOrderAsync(orderSaveParameters, null);
        }
        
        /// <remarks/>
        public void saveOrderAsync(orderSaveParameters orderSaveParameters, object userState) {
            if ((this.saveOrderOperationCompleted == null)) {
                this.saveOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveOrderOperationCompleted);
            }
            this.InvokeAsync("saveOrder", new object[] {
                        orderSaveParameters}, this.saveOrderOperationCompleted, userState);
        }
        
        private void OnsaveOrderOperationCompleted(object arg) {
            if ((this.saveOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveOrderCompleted(this, new saveOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://im.se/webservices/c3pl", ResponseNamespace="http://im.se/webservices/c3pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public order validateOrder([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] orderSaveParameters orderSaveParameters) {
            object[] results = this.Invoke("validateOrder", new object[] {
                        orderSaveParameters});
            return ((order)(results[0]));
        }
        
        /// <remarks/>
        public void validateOrderAsync(orderSaveParameters orderSaveParameters) {
            this.validateOrderAsync(orderSaveParameters, null);
        }
        
        /// <remarks/>
        public void validateOrderAsync(orderSaveParameters orderSaveParameters, object userState) {
            if ((this.validateOrderOperationCompleted == null)) {
                this.validateOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateOrderOperationCompleted);
            }
            this.InvokeAsync("validateOrder", new object[] {
                        orderSaveParameters}, this.validateOrderOperationCompleted, userState);
        }
        
        private void OnvalidateOrderOperationCompleted(object arg) {
            if ((this.validateOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateOrderCompleted(this, new validateOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://im.se/webservices/c3pl", ResponseNamespace="http://im.se/webservices/c3pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customerOrderTypeSearchResult getCustomerOrderTypes() {
            object[] results = this.Invoke("getCustomerOrderTypes", new object[0]);
            return ((customerOrderTypeSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerOrderTypesAsync() {
            this.getCustomerOrderTypesAsync(null);
        }
        
        /// <remarks/>
        public void getCustomerOrderTypesAsync(object userState) {
            if ((this.getCustomerOrderTypesOperationCompleted == null)) {
                this.getCustomerOrderTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerOrderTypesOperationCompleted);
            }
            this.InvokeAsync("getCustomerOrderTypes", new object[0], this.getCustomerOrderTypesOperationCompleted, userState);
        }
        
        private void OngetCustomerOrderTypesOperationCompleted(object arg) {
            if ((this.getCustomerOrderTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerOrderTypesCompleted(this, new getCustomerOrderTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://im.se/webservices/c3pl", ResponseNamespace="http://im.se/webservices/c3pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public methodOfShipmentSearchResult getMethodOfShipments([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] methodOfShipmentSearchParameters MethodOfShipmentSearchParameters) {
            object[] results = this.Invoke("getMethodOfShipments", new object[] {
                        MethodOfShipmentSearchParameters});
            return ((methodOfShipmentSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void getMethodOfShipmentsAsync(methodOfShipmentSearchParameters MethodOfShipmentSearchParameters) {
            this.getMethodOfShipmentsAsync(MethodOfShipmentSearchParameters, null);
        }
        
        /// <remarks/>
        public void getMethodOfShipmentsAsync(methodOfShipmentSearchParameters MethodOfShipmentSearchParameters, object userState) {
            if ((this.getMethodOfShipmentsOperationCompleted == null)) {
                this.getMethodOfShipmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMethodOfShipmentsOperationCompleted);
            }
            this.InvokeAsync("getMethodOfShipments", new object[] {
                        MethodOfShipmentSearchParameters}, this.getMethodOfShipmentsOperationCompleted, userState);
        }
        
        private void OngetMethodOfShipmentsOperationCompleted(object arg) {
            if ((this.getMethodOfShipmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMethodOfShipmentsCompleted(this, new getMethodOfShipmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class orderSearchParameters : baseParameters {
        
        private System.Nullable<orderType> orderTypeField;
        
        private string orderNoField;
        
        private string yourConoField;
        
        private System.Nullable<System.DateTime> fromField;
        
        private System.Nullable<System.DateTime> toField;
        
        private string markField;
        
        private bool ordersFromProductionField;
        
        private bool ordersFromHistoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<orderType> orderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string yourCono {
            get {
                return this.yourConoField;
            }
            set {
                this.yourConoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool ordersFromProduction {
            get {
                return this.ordersFromProductionField;
            }
            set {
                this.ordersFromProductionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool ordersFromHistory {
            get {
                return this.ordersFromHistoryField;
            }
            set {
                this.ordersFromHistoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public enum orderType {
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        CO3PL,
        
        /// <remarks/>
        PO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(methodOfShipmentSearchParameters))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(orderSaveParameters))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(orderSearchParameters))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class baseParameters {
        
        private string clientIdField;
        
        private bool returnDetailsField;
        
        private System.Nullable<int> firstResultField;
        
        private System.Nullable<int> maxResultField;
        
        private string stockNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool returnDetails {
            get {
                return this.returnDetailsField;
            }
            set {
                this.returnDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> firstResult {
            get {
                return this.firstResultField;
            }
            set {
                this.firstResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> maxResult {
            get {
                return this.maxResultField;
            }
            set {
                this.maxResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string stockNo {
            get {
                return this.stockNoField;
            }
            set {
                this.stockNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class customerOrderType {
        
        private string customerOrderTypeIdField;
        
        private string customerOrderTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerOrderTypeId {
            get {
                return this.customerOrderTypeIdField;
            }
            set {
                this.customerOrderTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerOrderTypeName {
            get {
                return this.customerOrderTypeNameField;
            }
            set {
                this.customerOrderTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class methodOfShipment {
        
        private string methodOfShipmentIdField;
        
        private string methodOfShipmentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string methodOfShipmentId {
            get {
                return this.methodOfShipmentIdField;
            }
            set {
                this.methodOfShipmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string methodOfShipmentName {
            get {
                return this.methodOfShipmentNameField;
            }
            set {
                this.methodOfShipmentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerOrderTypeSearchResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(methodOfShipmentSearchResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(orderSearchResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class searchResult {
        
        private int totalHitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int totalHits {
            get {
                return this.totalHitsField;
            }
            set {
                this.totalHitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class customerOrderTypeSearchResult : searchResult {
        
        private customerOrderType[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customerOrderType[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class methodOfShipmentSearchResult : searchResult {
        
        private methodOfShipment[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public methodOfShipment[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class orderSearchResult : searchResult {
        
        private order[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public order[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class order {
        
        private orderType orderTypeField;
        
        private bool orderTypeFieldSpecified;
        
        private string coNoField;
        
        private string customerField;
        
        private string cuRefField;
        
        private string yourConoField;
        
        private System.Nullable<System.DateTime> reqDelDateField;
        
        private string textField;
        
        private string coMarkField;
        
        private shippingAddress shippingAddressField;
        
        private orderLine[] orderLinesField;
        
        private string poidField;
        
        private System.Nullable<int> poSeqField;
        
        private string receivingWhidField;
        
        private string shipFromPartyidField;
        
        private string whNameField;
        
        private orderShipFrom orderShipFromField;
        
        private string methodOfShipmentIdField;
        
        private string methodOfShipmentNameField;
        
        private string customerOrderTypeIdField;
        
        private string customerOrderTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public orderType orderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderTypeSpecified {
            get {
                return this.orderTypeFieldSpecified;
            }
            set {
                this.orderTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coNo {
            get {
                return this.coNoField;
            }
            set {
                this.coNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuRef {
            get {
                return this.cuRefField;
            }
            set {
                this.cuRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string yourCono {
            get {
                return this.yourConoField;
            }
            set {
                this.yourConoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> reqDelDate {
            get {
                return this.reqDelDateField;
            }
            set {
                this.reqDelDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coMark {
            get {
                return this.coMarkField;
            }
            set {
                this.coMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shippingAddress shippingAddress {
            get {
                return this.shippingAddressField;
            }
            set {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("orderLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public orderLine[] orderLines {
            get {
                return this.orderLinesField;
            }
            set {
                this.orderLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string poid {
            get {
                return this.poidField;
            }
            set {
                this.poidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> poSeq {
            get {
                return this.poSeqField;
            }
            set {
                this.poSeqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receivingWhid {
            get {
                return this.receivingWhidField;
            }
            set {
                this.receivingWhidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipFromPartyid {
            get {
                return this.shipFromPartyidField;
            }
            set {
                this.shipFromPartyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string whName {
            get {
                return this.whNameField;
            }
            set {
                this.whNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public orderShipFrom orderShipFrom {
            get {
                return this.orderShipFromField;
            }
            set {
                this.orderShipFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string methodOfShipmentId {
            get {
                return this.methodOfShipmentIdField;
            }
            set {
                this.methodOfShipmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string methodOfShipmentName {
            get {
                return this.methodOfShipmentNameField;
            }
            set {
                this.methodOfShipmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerOrderTypeId {
            get {
                return this.customerOrderTypeIdField;
            }
            set {
                this.customerOrderTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerOrderTypeName {
            get {
                return this.customerOrderTypeNameField;
            }
            set {
                this.customerOrderTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class shippingAddress {
        
        private string shipCustNoField;
        
        private string shiptoNoField;
        
        private address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipCustNo {
            get {
                return this.shipCustNoField;
            }
            set {
                this.shipCustNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shiptoNo {
            get {
                return this.shiptoNoField;
            }
            set {
                this.shiptoNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class address {
        
        private string name1Field;
        
        private string name2Field;
        
        private string street1Field;
        
        private string street2Field;
        
        private string street3Field;
        
        private string zipCodeField;
        
        private string cityField;
        
        private string stateCdField;
        
        private string countryCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name2 {
            get {
                return this.name2Field;
            }
            set {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string street3 {
            get {
                return this.street3Field;
            }
            set {
                this.street3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stateCd {
            get {
                return this.stateCdField;
            }
            set {
                this.stateCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string countryCd {
            get {
                return this.countryCdField;
            }
            set {
                this.countryCdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class orderLine {
        
        private string partNoField;
        
        private string partDescr1Field;
        
        private string partDescr2Field;
        
        private string custPartNoField;
        
        private string custPartDescr1Field;
        
        private string custPartDescr2Field;
        
        private string textField;
        
        private System.Nullable<decimal> qtyUnitField;
        
        private System.Nullable<decimal> originalQtyUnitField;
        
        private string unitField;
        
        private string unitDescrField;
        
        private System.Nullable<int> linePosField;
        
        private System.Nullable<int> lineSeqField;
        
        private System.Nullable<int> lineIdField;
        
        private string sellingUnitField;
        
        private string sellingUnitDescField;
        
        private System.Nullable<System.DateTime> delDateField;
        
        private System.Nullable<int> lineStatusField;
        
        private System.Nullable<decimal> rcvQtyUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partNo {
            get {
                return this.partNoField;
            }
            set {
                this.partNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partDescr1 {
            get {
                return this.partDescr1Field;
            }
            set {
                this.partDescr1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partDescr2 {
            get {
                return this.partDescr2Field;
            }
            set {
                this.partDescr2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string custPartNo {
            get {
                return this.custPartNoField;
            }
            set {
                this.custPartNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string custPartDescr1 {
            get {
                return this.custPartDescr1Field;
            }
            set {
                this.custPartDescr1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string custPartDescr2 {
            get {
                return this.custPartDescr2Field;
            }
            set {
                this.custPartDescr2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> qtyUnit {
            get {
                return this.qtyUnitField;
            }
            set {
                this.qtyUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> originalQtyUnit {
            get {
                return this.originalQtyUnitField;
            }
            set {
                this.originalQtyUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unitDescr {
            get {
                return this.unitDescrField;
            }
            set {
                this.unitDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> linePos {
            get {
                return this.linePosField;
            }
            set {
                this.linePosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> lineSeq {
            get {
                return this.lineSeqField;
            }
            set {
                this.lineSeqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> lineId {
            get {
                return this.lineIdField;
            }
            set {
                this.lineIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sellingUnit {
            get {
                return this.sellingUnitField;
            }
            set {
                this.sellingUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sellingUnitDesc {
            get {
                return this.sellingUnitDescField;
            }
            set {
                this.sellingUnitDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<System.DateTime> delDate {
            get {
                return this.delDateField;
            }
            set {
                this.delDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> lineStatus {
            get {
                return this.lineStatusField;
            }
            set {
                this.lineStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> rcvQtyUnit {
            get {
                return this.rcvQtyUnitField;
            }
            set {
                this.rcvQtyUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class orderShipFrom {
        
        private string shipFromPartyidField;
        
        private partyType shipFromPartyQualifierField;
        
        private bool shipFromPartyQualifierFieldSpecified;
        
        private address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipFromPartyid {
            get {
                return this.shipFromPartyidField;
            }
            set {
                this.shipFromPartyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public partyType shipFromPartyQualifier {
            get {
                return this.shipFromPartyQualifierField;
            }
            set {
                this.shipFromPartyQualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shipFromPartyQualifierSpecified {
            get {
                return this.shipFromPartyQualifierFieldSpecified;
            }
            set {
                this.shipFromPartyQualifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public enum partyType {
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        GO,
        
        /// <remarks/>
        OT,
        
        /// <remarks/>
        SU,
        
        /// <remarks/>
        WH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class methodOfShipmentSearchParameters : baseParameters {
        
        private string clientId1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clientId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientId1 {
            get {
                return this.clientId1Field;
            }
            set {
                this.clientId1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/webservices/c3pl")]
    public partial class orderSaveParameters : baseParameters {
        
        private order orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public order order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getOpenOrdersCompletedEventHandler(object sender, getOpenOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOpenOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOpenOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public orderSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((orderSearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getOrderDetailsCompletedEventHandler(object sender, getOrderDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrderDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrderDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public order Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((order)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void saveOrderCompletedEventHandler(object sender, saveOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public order Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((order)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void validateOrderCompletedEventHandler(object sender, validateOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public order Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((order)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getCustomerOrderTypesCompletedEventHandler(object sender, getCustomerOrderTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerOrderTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerOrderTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public customerOrderTypeSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((customerOrderTypeSearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getMethodOfShipmentsCompletedEventHandler(object sender, getMethodOfShipmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMethodOfShipmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMethodOfShipmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public methodOfShipmentSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((methodOfShipmentSearchResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591