/*
  File           : 

  Description    : Interface classes for inbound data.
                   This code was generated, do not edit.

*/
using System;
using System.Data;
using System.Xml.Serialization;

namespace Imi.Wms.WebServices.OutboundTesterMAPI
{
  public class ExternalInterface
  {
    public string _Debug()
    {
      return "Generated on   : 2008-05-12 13:33:58\r\n" +
             "Generated by   : SWG\\olla@IMIPC1091\r\n" +
             "Generated in   : C:\\project\\views\\olla_dotnet_ss\\dotnet\\source\\CodeGenerators\\wscc\r\n";
    }
  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class MovementIn_01Doc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string             OPCODE;                /* .                                         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             OperationalCode;       /* MAPI_OUT_MOVM_IN_01.OPERATIONALCODE       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ItemLoadIdentity;      /* MAPI_OUT_MOVM_IN_01.ITEMLOADIDENTITY      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ProductNumber;         /* MAPI_OUT_MOVM_IN_01.PRODUCTNUMBER         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> FifoDate;              /* MAPI_OUT_MOVM_IN_01.FIFODATE              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             HoldCode;              /* MAPI_OUT_MOVM_IN_01.HOLDCODE              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ProductionLotIdentity; /* MAPI_OUT_MOVM_IN_01.PRODUCTIONLOTIDENTITY */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> CreatedDate;           /* MAPI_OUT_MOVM_IN_01.CREATEDDATE           */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class MovementOut_01Doc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string        OPCODE;                /* .                                          */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string        OperationalCode;       /* MAPI_OUT_MOVM_OUT_01.OPERATIONALCODE       */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<int> MovementOrderIdentity; /* MAPI_OUT_MOVM_OUT_01.MOVEMENTORDERIDENTITY */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string        MovementOrderType;     /* MAPI_OUT_MOVM_OUT_01.MOVEMENTORDERTYPE     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string        ProductNumber;         /* MAPI_OUT_MOVM_OUT_01.PRODUCTNUMBER         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string        ToLocationAddress;     /* MAPI_OUT_MOVM_OUT_01.TOLOCATIONADDRESS     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<int> MovementPriority;      /* MAPI_OUT_MOVM_OUT_01.MOVEMENTPRIORITY      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string        ProductionLotIdentity; /* MAPI_OUT_MOVM_OUT_01.PRODUCTIONLOTIDENTITY */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string        ItemLoadIdentity;      /* MAPI_OUT_MOVM_OUT_01.ITEMLOADIDENTITY      */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class Product_01Doc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string           OPCODE;               /* .                                        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           OperationalCode;      /* MAPI_OUT_PRODUCT_01.OPERATIONALCODE      */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           ProductNumber;        /* MAPI_OUT_PRODUCT_01.PRODUCTNUMBER        */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           BarCode;              /* MAPI_OUT_PRODUCT_01.BARCODE              */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           ProductDescription1;  /* MAPI_OUT_PRODUCT_01.PRODUCTDESCRIPTION1  */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           HandlingUnitIdentity; /* MAPI_OUT_PRODUCT_01.HANDLINGUNITIDENTITY */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           BestBeforDateFlag;    /* MAPI_OUT_PRODUCT_01.BESTBEFORDATEFLAG    */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<double> NumberOfBasePackageS; /* MAPI_OUT_PRODUCT_01.NUMBEROFBASEPACKAGES */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string           BatchType;            /* MAPI_OUT_PRODUCT_01.BATCHTYPE            */


  }

  [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://im.se/wms/webservices/")]
  public class StatusUpdate_01Doc
  {
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
    public string             OPCODE;           /* .                                     */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             ItemLoadIdentity; /* MAPI_OUT_STAT_UPD_01.ITEMLOADIDENTITY */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Nullable<DateTime> FifoDate;         /* MAPI_OUT_STAT_UPD_01.FIFODATE         */

    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string             HoldCode;         /* MAPI_OUT_STAT_UPD_01.HOLDCODE         */


  }

}
