select   RPT.RPTID
        ,RPT.RPTGRPID
        ,RPT.RPT_FILE
	    ,RPT.UPDDTM
		,RPT_ADAPTER.ADAPTER_ID
		,RPT_ADAPTER.UPDDTM ADAPTERUPDDTM
  from   RPT
        ,RPT_ADAPTER
  where  RPT_ADAPTER.RPTID(+) = RPT.RPTID
  order by RPT_ADAPTER.SEQNUM ASC