USE [master]
GO

/****** Object:  Database [SmartClientUserSettings]    Script Date: 2016-04-14 10:43:37 ******/
CREATE DATABASE [SmartClientUserSettings]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmartClientUserSettings', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SmartClientUserSettings.mdf' , SIZE = 30720KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'SmartClientUserSettings_log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SmartClientUserSettings_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 50%)
GO

ALTER DATABASE [SmartClientUserSettings] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmartClientUserSettings].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SmartClientUserSettings] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET ARITHABORT OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SmartClientUserSettings] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SmartClientUserSettings] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SmartClientUserSettings] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SmartClientUserSettings] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SmartClientUserSettings] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SmartClientUserSettings] SET  MULTI_USER 
GO

ALTER DATABASE [SmartClientUserSettings] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SmartClientUserSettings] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SmartClientUserSettings] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SmartClientUserSettings] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SmartClientUserSettings] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SmartClientUserSettings] SET  READ_WRITE 
GO


