SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BlobMetaData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BlobId] [int] NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Value] [nvarchar](512) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BlobStore](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](512) NOT NULL,
	[LastModified] [datetime] NULL,
	[ContainerId] [int] NULL,
	[Data] [ntext] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Container](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](512) NOT NULL,
	[LastModified] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ContainerMetaData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ContainerId] [int] NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Value] [nvarchar](512) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ContainerMetaData]  WITH CHECK ADD  CONSTRAINT [FK_ContainerMetaData_Container] FOREIGN KEY([ContainerId])
REFERENCES [dbo].[Container] ([Id])
GO

ALTER TABLE [dbo].[ContainerMetaData] CHECK CONSTRAINT [FK_ContainerMetaData_Container]
GO

ALTER TABLE [dbo].[BlobStore]  WITH CHECK ADD  CONSTRAINT [FK_Blob_Container] FOREIGN KEY([ContainerId])
REFERENCES [dbo].[Container] ([Id])
GO

ALTER TABLE [dbo].[BlobStore] CHECK CONSTRAINT [FK_Blob_Container]
GO

ALTER TABLE [dbo].[BlobMetaData]  WITH CHECK ADD  CONSTRAINT [FK_BlobMetaData_Blob] FOREIGN KEY([BlobId])
REFERENCES [dbo].[BlobStore] ([Id])
GO

ALTER TABLE [dbo].[BlobMetaData] CHECK CONSTRAINT [FK_BlobMetaData_Blob]
GO