//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService {
    using global::System.Runtime.Serialization;
    using global::System;
    
    
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.Runtime.Serialization", "4.0.0.0")]
    [global::System.Runtime.Serialization.DataContractAttribute(Name="CreateSessionParams", Namespace="http://Cdc.SupplyChain.Services.global::System.Session.DataContracts/2007/05")]
    [global::System.SerializableAttribute()]
    public partial class CreateSessionParams : object, global::System.Runtime.Serialization.IExtensibleDataObject, global::System.ComponentModel.INotifyPropertyChanged {
        
        [global::System.NonSerializedAttribute()]
        private global::System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            global::System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.Runtime.Serialization", "4.0.0.0")]
    [global::System.Runtime.Serialization.DataContractAttribute(Name="CreateSessionResultParams", Namespace="http://Cdc.SupplyChain.Services.global::System.Session.DataContracts/2007/05")]
    [global::System.SerializableAttribute()]
    public partial class CreateSessionResultParams : object, global::System.Runtime.Serialization.IExtensibleDataObject, global::System.ComponentModel.INotifyPropertyChanged {
        
        [global::System.NonSerializedAttribute()]
        private global::System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            global::System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.Runtime.Serialization", "4.0.0.0")]
    [global::System.Runtime.Serialization.DataContractAttribute(Name="AbortTransactionParams", Namespace="http://Cdc.SupplyChain.Services.global::System.Session.DataContracts/2007/05")]
    [global::System.SerializableAttribute()]
    public partial class AbortTransactionParams : object, global::System.Runtime.Serialization.IExtensibleDataObject, global::System.ComponentModel.INotifyPropertyChanged {
        
        [global::System.NonSerializedAttribute()]
        private global::System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            global::System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.ServiceModel", "4.0.0.0")]
    [global::System.ServiceModel.ServiceContractAttribute(Namespace="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05", ConfigurationName="SessionService.ISessionService")]
    public interface ISessionService {
        
        // CODEGEN: Generating message contract since the wrapper name (CreateSessionRequest) of message CreateSessionRequest does not match the default value (CreateSession)
        [global::System.ServiceModel.OperationContractAttribute(Action="CreateSession", ReplyAction="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05/ISessionS" +
            "ervice/CreateSessionResponse")]
        [global::System.ServiceModel.FaultContractAttribute(typeof(Cdc.Framework.Services.SystemFault), Action="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05/ISessionS" +
            "ervice/CreateSessionSystemFaultFault", Name="SystemFault", Namespace="http://www.im.se/framework/services/systemfault/2007/05")]
        [global::System.ServiceModel.FaultContractAttribute(typeof(Cdc.Framework.Services.ApplicationFault), Action="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05/ISessionS" +
            "ervice/CreateSessionApplicationFaultFault", Name="ApplicationFault", Namespace="http://www.im.se/framework/services/applicationfault/2007/05")]
        Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionResponse CreateSession(Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionRequest request);
        
        // CODEGEN: Generating message contract since the operation AbortTransaction is neither RPC nor document wrapped.
        [global::System.ServiceModel.OperationContractAttribute(Action="AbortTransaction", ReplyAction="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05/ISessionS" +
            "ervice/AbortTransactionResponse")]
        [global::System.ServiceModel.FaultContractAttribute(typeof(Cdc.Framework.Services.SystemFault), Action="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05/ISessionS" +
            "ervice/AbortTransactionSystemFaultFault", Name="SystemFault", Namespace="http://www.im.se/framework/services/systemfault/2007/05")]
        [global::System.ServiceModel.FaultContractAttribute(typeof(Cdc.Framework.Services.ApplicationFault), Action="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05/ISessionS" +
            "ervice/AbortTransactionApplicationFaultFault", Name="ApplicationFault", Namespace="http://www.im.se/framework/services/applicationfault/2007/05")]
        Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionResponse AbortTransaction(Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionRequest request);
    }
    
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.ServiceModel", "4.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    [global::System.ServiceModel.MessageContractAttribute(WrapperName="CreateSessionRequest", WrapperNamespace="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05", IsWrapped=true)]
    public partial class CreateSessionRequest {
        
        [global::System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05", Order=0)]
        public Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionParams CreateSessionParams;
        
        public CreateSessionRequest() {
        }
        
        public CreateSessionRequest(Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionParams CreateSessionParams) {
            this.CreateSessionParams = CreateSessionParams;
        }
    }
    
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.ServiceModel", "4.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    [global::System.ServiceModel.MessageContractAttribute(WrapperName="CreateSessionResponse", WrapperNamespace="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05", IsWrapped=true)]
    public partial class CreateSessionResponse {
        
        [global::System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05", Order=0)]
        public Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionResultParams CreateSessionResultParams;
        
        public CreateSessionResponse() {
        }
        
        public CreateSessionResponse(Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionResultParams CreateSessionResultParams) {
            this.CreateSessionResultParams = CreateSessionResultParams;
        }
    }
    
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.ServiceModel", "4.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    [global::System.ServiceModel.MessageContractAttribute(WrapperName="AbortTransactionRequest", WrapperNamespace="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05", IsWrapped=true)]
    public partial class AbortTransactionRequest {
        
        [global::System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.im.se/framework/services")]
        public string SessionId;
        
        [global::System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.im.se/framework/services")]
        public string TransactionId;
        
        [global::System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Cdc.SupplyChain.Services.global::System.Session.ServiceContracts/2007/05", Order=0)]
        public Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionParams AbortTransactionParams;
        
        public AbortTransactionRequest() {
        }
        
        public AbortTransactionRequest(string SessionId, string TransactionId, Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionParams AbortTransactionParams) {
            this.SessionId = SessionId;
            this.TransactionId = TransactionId;
            this.AbortTransactionParams = AbortTransactionParams;
        }
    }
    
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.ServiceModel", "4.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    [global::System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AbortTransactionResponse {
        
        public AbortTransactionResponse() {
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.ServiceModel", "4.0.0.0")]
    public interface ISessionServiceChannel : Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.ISessionService, global::System.ServiceModel.IClientChannel {
    }
    
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.ServiceModel", "4.0.0.0")]
    public partial class SessionServiceClient : global::System.ServiceModel.ClientBase<Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.ISessionService>, Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.ISessionService {
        
        public SessionServiceClient() {
        }
        
        public SessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, global::System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(global::System.ServiceModel.Channels.Binding binding, global::System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionResponse Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.ISessionService.CreateSession(Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionRequest request) {
            return base.Channel.CreateSession(request);
        }
        
        public Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionResultParams CreateSession(Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionParams CreateSessionParams) {
            Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionRequest inValue = new Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionRequest();
            inValue.CreateSessionParams = CreateSessionParams;
            Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.CreateSessionResponse retVal = ((Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.ISessionService)(this)).CreateSession(inValue);
            return retVal.CreateSessionResultParams;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionResponse Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.ISessionService.AbortTransaction(Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionRequest request) {
            return base.Channel.AbortTransaction(request);
        }
        
        public void AbortTransaction(string SessionId, string TransactionId, Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionParams AbortTransactionParams) {
            Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionRequest inValue = new Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionRequest();
            inValue.SessionId = SessionId;
            inValue.TransactionId = TransactionId;
            inValue.AbortTransactionParams = AbortTransactionParams;
            Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.AbortTransactionResponse retVal = ((Cdc.SupplyChain.Services.System.MobileAuthentication.DataAccess.SessionService.ISessionService)(this)).AbortTransaction(inValue);
        }
    }
}
