//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Imi.SupplyChain.Server.Job.CentiroAdapter.DataEntities {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CentiroPrintParcels {
        
        private CentiroPrintParcelsParcels parcelsField;
        
        private string senderCodeField;
        
        private string shipmentIdentifierField;
        
        private string returnSequenceNumbersField;
        
        private string returnTrackingUrlsField;
        
        private string userField;
        
        private string terminalField;
        
        private int numberOfTagsField;
        
        private bool numberOfTagsFieldSpecified;
        
        private string printerIdentityField;
        
        private string urlField;
        
        /// <remarks/>
        public CentiroPrintParcelsParcels Parcels {
            get {
                return this.parcelsField;
            }
            set {
                this.parcelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string senderCode {
            get {
                return this.senderCodeField;
            }
            set {
                this.senderCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shipmentIdentifier {
            get {
                return this.shipmentIdentifierField;
            }
            set {
                this.shipmentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returnSequenceNumbers {
            get {
                return this.returnSequenceNumbersField;
            }
            set {
                this.returnSequenceNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string returnTrackingUrls {
            get {
                return this.returnTrackingUrlsField;
            }
            set {
                this.returnTrackingUrlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numberOfTags {
            get {
                return this.numberOfTagsField;
            }
            set {
                this.numberOfTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberOfTagsSpecified {
            get {
                return this.numberOfTagsFieldSpecified;
            }
            set {
                this.numberOfTagsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string printerIdentity {
            get {
                return this.printerIdentityField;
            }
            set {
                this.printerIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CentiroPrintParcelsParcels {
        
        private CentiroPrintParcelType[] parcelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parcel")]
        public CentiroPrintParcelType[] Parcel {
            get {
                return this.parcelField;
            }
            set {
                this.parcelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CentiroPrintParcelType {
        
        private string parcelIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parcelIdentifier {
            get {
                return this.parcelIdentifierField;
            }
            set {
                this.parcelIdentifierField = value;
            }
        }
    }
}
